### ISSUE TITLE
can't get DOM bindings to work

### ISSUE THREAD

**Issue by hyperborea** [diegomura/react-pdf#101]
I tried to make the package work in the browser, but ran into a bunch of issues along the way:
- the official example uses an outdated version of `@react-pdf/dom (0.1.6)` referencing the wrong core package (`react-pdf` instead of `@react-pdf/core`)
- browser environments don't provide fs, tls and net. create-react-app conveniently mocks them out, but I figured to still mention it for people using a different setup
- with above two points fixed I'm still getting below error, which I wasn't able to resolve yet
<img width="712" alt="screen shot 2017-06-24 at 12 31 46" src="https://user-images.githubusercontent.com/5477116/27507870-700dca60-58d9-11e7-9b33-4efc8ec56a7a.png">

Does anyone know what's the matter or has a local setup that works browser-side?

**Comment by hyperborea** [comment]
Adding babel-polyfill to `@react-pdf/core` adds support for async generators, but then the problems continue: 
<img width="709" alt="screen shot 2017-06-24 at 13 59 13" src="https://user-images.githubusercontent.com/5477116/27508465-ba7202a4-58e5-11e7-97fd-513df07d22f2.png">

If anyone could provide me with a working example that would be great.

**Comment by diegomura** [comment]
Hi @hyperborea .
Thanks for reporting all these issues.

We are still working on supporting react-pdf to the dom. A while ago we switch from using our own pdf bindings to use `pdfkit`. I'm not into this subject so much (@jbovenschen is, maybe he can give more info about it), but `pdfkit` has some issues working in the browser with webpack. @jbovenschen is on it, but I'm not sure if he had some progress yet. I was planning on helping him, since this is an important issue to the project. So I think the `fs` error is because of this.

About the other things, I will:
- Fix the examples dependencies issues.
- Add `babel-polyfill` to `@react-pdf/core`

I'll keep this issue opened to let other people know about this, and also to let people say if he/she wants to help on this.

**Comment by hyperborea** [comment]
Thanks @diegomura, I'm having high hopes for this project and look forward to see how it develops. Fingers crossed that browser support is coming back soon, I'd ideally like to use it in both environments in parallel.

PS: adding babel-polyfill is probably overkill, best check out the last point under "Troubleshooting" here: https://www.npmjs.com/package/babel-watch.

**Comment by jbovenschen** [comment]
@hyperborea After we switched to using `pdfkit` it started to not work for us anymore. Because the main build of `pdfkit` depends on node internals for it to behave correctly, this can be solved by bundling them using `webpack` or `browserify`. But that would make our library huge.

Some weeks ago I started to work on doing the things we need to do to make `pdfkit` easy to use for our end users. But don't have a lot of time the upcoming weeks, sorry for that. 

The things I need to do to make the `pdfkit` library useful for our end are;

- [ ] Converting to babel instead of coffeescript (Currently working on this).
- [ ] Bundle the library through rollup.
- [ ] Provide smaller shims for the node internals for the browser version.

Could definitely use some help, because I don't have that much time to spend currently.

About the regeneratorRuntime that is an issue on our side, this because we depend on babel-polyfills we don't provide, we really should fix this in an upcoming release, my strategy for this one is that we just would include babel-runtime and babel-preset-env and point it to the lowest browser we tend to support in react-pdf.

**Comment by tuananhtd** [comment]
@jbovenschen I thought `pdfkit` work fine in browser on it own? which node internals we need? Btw what do you mean by "converting to babel instead of coffeescript". I know the `pdfkit` lib is written in coffeescript but we're already use babel right?

**Comment by jbovenschen** [comment]
It works kinda work, if we add a compiled version with browserify of pdfkit to the project, only this includes node specific packages which create a lot of unnecessary overhead, could be a lot smaller if we shim the needed parts with browser specific API's. 

If you want to try to get it running with a compiled version inside the project I will take a look to improve it when I have some spare time for it.

**Comment by SPAHI4** [comment]
for me it can't find `net` module, when it's running from browser.

**Comment by bkoltai** [comment]
Does someone have this working in the browser? I would really like to use it for client-side PDF generation. 

If you do, can you please provide a list of steps to get it going?
If not, what is the list of things that need to get done in the project?

**Comment by jbovenschen** [comment]
I'm currently trying to get it working with a custom pdfkit build, need to do some changes but I guess I am nearly there. The thing is don't have custom font rendering working ATM. Hopefully I can finish it this weekend.

**Comment by diegomura** [comment]
That's awesome @jbovenschen !! Ping if you need help!

**Comment by ngbinh** [comment]
any update on this issue? Thanks
