### ISSUE TITLE
help needed using the library.

### ISSUE THREAD

**Issue by maitedev** [diegomura/react-pdf#1043]
Hi, I want to use the library in my project, for that I first wanted to do a little sandbox test with one of the examples provided. I do not know what I can be doing or using wrong, because I only get a blank box.
Any help is very welcome.

https://codesandbox.io/s/intelligent-mcnulty-9426g?file=/src/index.js

Thanks in advance

**Comment by prahladjshenoy** [comment]
React renderer for creating PDF files on the browser and server. So that u can create and view pdf on browser.
 
The black box you get was the PDFViewer so that u can view the pdf. If u add CSS you can view it large.
 
![image](https://user-images.githubusercontent.com/50204019/98439338-44f7ff80-2117-11eb-857d-de6d0ef16edf.png)

**Comment by diegomura** [comment]
Thanks @prahladjshenoy
