### ISSUE TITLE
Split named exports into separate files to have possibility to lazy load

### ISSUE THREAD

**Issue by mariia-kulakova** [diegomura/react-pdf#1119]
It would be great to import not just in this way:
`import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';`
but also something like:
```
import Document from '@react-pdf/renderer/Document';
import Page from '@react-pdf/renderer/Page';
...
```
to have a possibility to lazy load react-pdf library

**Comment by diegomura** [comment]
This is not possible unfortunately, since `Page`, `Document` and any other primitive is just a string (try console.log them). I thought about this in the past but it's simply not possible to tree-shake as you propose. In addition, there's actually no much bundle size you would be saving, maybe just in some specific scenarios such as images, but you will see that [most of the bundle size ](https://bundlephobia.com/result?p=@react-pdf/renderer@2.0.6)goes in shared things such as yoga and pdfkit. fontkit would be a bit save though, but most of the people uses text anyway. I'm open to ideas though if I'm missing something here. In the meantime, I'll close this. Thanks!
