### ISSUE TITLE
Image component breaks styles in entire file

### ISSUE THREAD

**Issue by RicardoGaefke** [diegomura/react-pdf#1153]
**Describe the bug**
When I insert an `<Image>` it breaks the style for entire PDF. This is the code:
```
      <View style={styles.imageWrapper}>
        <Image
          source="/img/locker.jpg"
          style={styles.image}
        />
      </View>

      <View style={styles.titleWrapper}>
        <Text style={styles.title}>
          {staticTitle(1)}
        </Text>
      </View>
```
If I comment the View and Image part the title and text are fine.

**Expected behavior**
Image to render WITHOUT breaking styles of texts.

**Screenshots**
Without `<Image>`
![image](https://user-images.githubusercontent.com/32141532/112382664-e3ea5600-8cca-11eb-85b9-464d203c88cc.png)
With `<Image>`
![image](https://user-images.githubusercontent.com/32141532/112382787-0c725000-8ccb-11eb-8c85-76b5b515adc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - "@react-pdf/renderer": "^1.6.13"

**Comment by diegomura** [comment]
Hi @RicardoGaefke . I'll need more information than that, at least what styles are being applied on each element and clear instructions about how to replicate it. Thanks!

**Comment by RicardoGaefke** [comment]
Hey @diegomura ... Thanks for your reply... this is the Styles file: [https://github.com/RicardoGaefke/profile4d/blob/dev/src/Web.Client/React/Components/Report/ReportPDF/Styles.ts](https://github.com/RicardoGaefke/profile4d/blob/dev/src/Web.Client/React/Components/Report/ReportPDF/Styles.ts)

And as it's a public repo all needed info is there.

Again, thank you very much.

**Comment by diegomura** [comment]
It's hard to reolicste since I still don't know exactly the issue here. Sorry, but the sippets are a bit confusing and the screenshots do not have a log of context. I just tested them though and everything seems to be rendered normally

[doc.pdf](https://github.com/diegomura/react-pdf/files/6269098/doc.pdf)

But don't have the same image or same text. Please upgrade to 2.0 though. I found out already that many bugs were fixed there.
