### ISSUE TITLE
[Support nested break] When adding multiple pagebreak, then page break doesn't work correct

### ISSUE THREAD

**Issue by duyank** [diegomura/react-pdf#1163]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl
2. Add all break attribute to Text element
3. Content in the last page was not interrupted

**Screenshots**
![image](https://user-images.githubusercontent.com/19285404/113468946-bdb77980-9473-11eb-8d11-2b5ac2cb512e.png)

**Comment by diegomura** [comment]
Thanks @duyank !

It will be fixed in the 2.0 version I plan to officially publish in just a couple of days (you can test it here in the meantime https://v2.react-pdf.org/repl). Feel free to update it and test it currently under `2.0.0-beta.20` in npm

**Comment by duyank** [comment]
Thank you,
I have checked v2. It seems ok with basic content.
But in my application. It has a nested `View` component. `break` prop doesn't work when I use it.
Do I have to use `break` in the parent view?
![image](https://user-images.githubusercontent.com/19285404/113470851-bea3d780-9482-11eb-83ea-bb13e428fc01.png)

**Comment by diegomura** [comment]
`break` does not have to be strictly in a parent view, but the parent view should be a component that wraps between at least 2 pages to work. The example you provided does not work on either v1 or v2. Page wrapping is a recursive process, and how it works for this case it first goes to the first (parent) view which does not break and fits in the page. So it stops there. 

I suggest you either change the issue to "Support nested break" or similar to reflect that if that's what you want. Doing nester breaks for these cases must be very hard to do though, since it will involve not just breaking the nested element but also stretching the parent element as well.

**Comment by duyank** [comment]
Thank you, I understood.
I will try to move all break elements to root elements.

> I suggest you either change the issue to "Support nested break"
I cannot add the label for issue so I updated the issue title

Can I ask question for v2 in PR below? 
https://github.com/diegomura/react-pdf/pull/617

**Comment by diegomura** [comment]
Sorry. This has been address before here: #1037. Closing this in favor of the other one.
