### ISSUE TITLE
Do we even need babel in the node package?

### ISSUE THREAD

**Issue by CentaurWarchief** [diegomura/react-pdf#120]
Newer versions of **node** already supports [**async/await**](https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf-node/src/index.js#L6) out of the box. But doesn't support **ES modules**. I think we could turn them into simple requires and get rid of babel dependency in the core package.

So, I'd love to use the library with minimum transpilation requirements as possible — since it isn't cool in the backend. Stack traces gets messy and sometimes it is just hard to catch errors.

Of course, that constrains the library usage to modern versions of node. Not sure about the ways we could use to... maintain support to legacy versions (if that's even a thing). Thoughts?

**Comment by diegomura** [comment]
I would also love to get rid of the transpiration step if it's not needed. My only concern is that async/await is supported in node from v7.6 and above, which was (I think) released early this year. There are lots of people using previous version of node. So here comes the same question you had: should we try supporting those? I actually don't know and I don't have any argue in favor or against this. @jbovenschen do you have any thoughts?

**Comment by CentaurWarchief** [comment]
Not sure how easy would it be to support 2 versions in parallel. 

But I think that: if we drop modules, but keep async/await. That'd be fine. Since most of the people that are using node < 7 for example are also using babel to transpile their code if they're using those features — hence, I don't think they'll be affected since the async/await will be transpiled as well and the syntax doesn't change.

Summarizing my boring comment above: we leave async/await, natively. Replace all imports/exports with plain-old require/`module.exports` statements. 

For those who are using node > 7, they won't have to use babel. For those who are below, but using babel, they're just fine.

Thoughts gentleman?

**Comment by CentaurWarchief** [comment]
I mean, we just relocate the babel requirement from our side to their side. If they have to.

**Comment by diegomura** [comment]
Makes total sense to me. I say we should go for it.
Do you want to create a PR for this?

**Comment by jbovenschen** [comment]
@CentaurWarchief the reason that it does need babel is because of stuff like async await like Diego mentioned already. 

Also we tend to support also using the package inside of the browser, if we want to support IE and other more older browser we just need the transpilation step inside `@react-pdf/core`.
I think I read somewhere that you can point bundlers and node to separate entry points inside the package. If so we wouldn't need to transpile all the stuff happening inside the `@react-pdf/core` package.

Also about the es2015 modules thing, I was thinking lately to bundle all our separate libraries with a bundler like `rollup` so we would not have any import statements anymore, and people can't import parts which we likely won't expose. Would this also solve something for you? 
Because es2015 modules are so handy to support tree-shaking in modern front-end bundling tools.

**Comment by CentaurWarchief** [comment]
> Also we tend to support also using the package inside of the browser, if we want to support IE and other more older browser we just need the transpilation step inside `@react-pdf/core`.

Fosho.

> Because es2015 modules are so handy to support tree-shaking in modern front-end bundling tools.

Totally. But like... we should have a node version that's imports-free (since it isn't supported natively yet and the idea is to reduce/remove transpilation for those).

Also, @diegomura — yes, up for it.

**Comment by diegomura** [comment]
Although everything you said its true @jbovenschen , I think we should get rid of the transpiling step just for the `node` package for the reasons @CentaurWarchief said. Of course we will still have it on the `dom` and `core` packages.

The only issue it may appear is someone trying to run `react-pdf-node` in a node version with no async/await support, which in that case he should (1) update his node version (2) take care of the transpiring him/herself.

I wouldn't worry that much about tree-shaking in this particular package, since it's a single file with no more than 25 lines :)

@CentaurWarchief look forward that PR!

**Comment by diegomura** [comment]
@CentaurWarchief @jbovenschen still up to this idea?

**Comment by CentaurWarchief** [comment]
heyo @diegomura — I think it's a nice idea, but unfortunately I still don't have time to work into it. You can close and set a label so we can find and reopen in the future.

Thanks for pinging!

**Comment by diegomura** [comment]
Deprecating `@react-pdf/node` package in favor of new isomorphic `@react-pdf/react-pdf` one. This issue got obsolete
