### ISSUE TITLE
border-top, border-right, etc. shorthands not working with styled-components

### ISSUE THREAD

**Issue by dyedwiper** [diegomura/react-pdf#1202]
**Describe the bug**
Using @react-pdf/styled-components the shorthands border-top, border-right, border-bottom and border-left do not work, while explicit declaration and the border shorthand work.

**To Reproduce**
https://codesandbox.io/s/wonderful-kirch-e4fwt?file=/src/Pdf.js

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by diegomura** [comment]
I recommend not using the styled-components anymore. First, the CSS support is not complete, and there's no much i can do on my side. Also, it relies on a very old styled-components version and it's not possible to upgrade since it's ta internal structure changed a lot. Also, it adds a lot of bundle size to your app since you will be basically shipping 2 styles-component implementations at the same time. I'll add this info to the styled-components repo soon. Thanks and sorry.
