### ISSUE TITLE
Add CSS grid support

### ISSUE THREAD

**Issue by AlexisMunozC** [diegomura/react-pdf#1207]
I want to add a dynamic footer in a specific page, I can't use neither margin bottom nor padding bottom because the height of my footer is dynamic. With Grid I could change the size of the content of the page using fr.

What could I do?

**Comment by diegomura** [comment]
Css gris is no likely to be implemented soon. This is mostly because we rely on Yoga for css layout and it's just a flex engine. Can leave this ticket open for future reference but just want to set up the expectations about this.

**Comment by diegomura** [comment]
Not sure what you are trying to do on your footer but you should be also able to achieve the same result with flex properties

**Comment by AlexisMunozC** [comment]
I want to make a page with footer where its height could be higher or lower depending on the content, and in the middle there is a table with some rows and I want the rows to continue on the next page if there is not enough space on the first page, How could i place the footer? I can't use absolute position because I have to add a paddingBottom to the page and I don't know the height of the footer, and I can't use fixed because I only want the footer on the first page 
![image](https://user-images.githubusercontent.com/40778810/114588406-e42f9e80-9c43-11eb-8d8f-70beff636a8f.png)

**Comment by diegomura** [comment]
I guess you could try defining the content element with `flex: 1` hoping it will fill the remaining page space every-time, no matter how big is the footer. However, I cannot guarantee it will work. As this ticket's title, CSS grid won't be supported anytime unfortunately. Not because I don't want to but because of the layout engine we use (Yoga layout) does not support it. There's no other engine we can use unfortunately :( Hope that works and feel free to open another ticket with the layout issue itself.

**Comment by AlexisMunozC** [comment]
I understand, thank you for your answer!!

**Comment by mattiaz9** [comment]
Maybe we should reopen this? At least since this issue is still open: https://github.com/facebook/yoga/issues/867

This feature would make it possible to create tables with cells using colspan and rowspan.
