### ISSUE TITLE
Instance "finish" method not defined on v2

### ISSUE THREAD

**Issue by ubinatus** [diegomura/react-pdf#1217]
**Describe the bug**
On the v2, the `finish` instance method from `pdf` is not defined. It was used to avoid memory leaks of further updates. The following example is another approach of downloading the PDF or getting its Blob, instead of using the given Components (`PDFDownloadLink` or `BlobProvider`, which doesn't fit our needs in this case).

      const instance = pdf(<Quixote />); // @react-pdf/renderer Document
      let blob = await instance.toBlob();
      instance.container.finish(); // finish is defined on v1 but not on v2

**To Reproduce**
1. Go to https://codesandbox.io/s/modern-pine-612md
2. Click the download button (it will download the Quixote PDF)
3. See the error on the console

**Expected behavior**
For obvious reasons, the error comes due that the `finish` container method on line 18 is not defined. When commented it works fine, but invoking the handler multiple times on large PDFs makes memory leaks. On the previous v1 version it was defined.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome v89
 - React-pdf version 2.0.3

**Comment by diegomura** [comment]
Hey!

Two things there:

- You should not need to keep calling `container.finish` since that logic is now being executed intenally for yoy
- Always bare in mind that `pdf` is not an official API (that's why it's not in the docs). When this project started I needed to export if for internal reasons, and now I keep exporting it since I realize many people used it, even though it was never in the docs or promoted. You can still use it, but just bare that in mind :)

**Comment by ubinatus** [comment]
@diegomura Thanks diego!
