### ISSUE TITLE
Is there any other way to access extended CSS apart from using the (deprecated) styled-components?

### ISSUE THREAD

**Issue by reinvanimschoot** [diegomura/react-pdf#1274]
Hi all

My team and I are looking to react-pdf as a replacement for paged.js since we have a React-based setup which would work better in combination with react-pdf.

That being said, we would require some more CSS rules than are currently supported in the stylesheet API. 

Despite the fact that it's deprecated, I assume using the react-pdf/styled-components package is the only way to do that? Or are we missing something?

Kind regards
Rein

**Comment by diegomura** [comment]
What CSS rules you require that the stylesheet API does not support? I cannot think right now of any property that you cannot use with the stylesheet api, specially since is what's being used to develop the library. Bare in mind that not every CSS property is supported in this lib, and currently there's no support for CSS selectors of any type

**Comment by reinvanimschoot** [comment]
@diegomura Specifically, I was indeed wondering if selectors were possible to use. But it seems they aren't, we'll have to find a workaround then. Thanks for the info!
