### ISSUE TITLE
Render Error, heights and others is not respect.

### ISSUE THREAD

**Issue by joacub** [diegomura/react-pdf#1296]
Broken heights and others, everything looks nasty now:

```
TypeError: Cannot read property 'props' of null
    at _callee$ (react-pdf.browser.es.js?cabe:207)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
    at eval (asyncToGenerator.js?1da1:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?1da1:21)
    at render (react-pdf.browser.es.js?cabe:232)
```

**Comment by diegomura** [comment]
Can you share the document you are trying to render?

**Comment by joacub** [comment]
<img width="299" alt="Screen Shot 2021-05-04 at 10 13 53 AM" src="https://user-images.githubusercontent.com/2091228/117017266-77974500-acc1-11eb-8609-23ac0360eb45.png">

**Comment by diegomura** [comment]
I was talking about the document code. A simplified version so I can replicate this is possible

**Comment by joacub** [comment]
> I was talking about the document code. A simplified version so I can replicate this is possible
the problem is the container is null always, see the error I sent first.

does not matter what document or code is, is always null

**Comment by joacub** [comment]
check this

 props = container.document.props || {};

**Comment by joacub** [comment]
im looking in what version start the error, and apparently is after 2.0.0, version 2.0.0 is ok next version start to not working

**Comment by joacub** [comment]
I saw the error, is about the flexBasis,
when flexBasis = 100% is not respecting the heights.

this is an example of the error:

```
flexGrow: 0,
    width: '100%',
    maxWidth: '100%',
    flexBasis: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
```

if I comment flexBasis everything works

**Comment by diegomura** [comment]
> the problem is the container is null always, see the error I sent first.
does not matter what document or code is, is always null

The error does not have much information. That's why the code does matter...
Glad you were able to reduce it to a single property. Are you using `PDFViewer` or how are you doing to render/visualize the doc?

**Comment by joacub** [comment]
we are using the pdf function to get the blob

**Comment by diegomura** [comment]
Just tried it and couldn't replicate. Check [here](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5401a920c01dc3b0ca004c30023047c66ce8013c00d866c01bcf5ad9300198e9401c4013884900b860006003447664a472a000b0701c801191d1c0148fd5d8d8518785001d53c7dfc8343c2dd84cc30500084782090209382c223232832506890ac3180a091c1fd40b498c1534b2878b490f8c0012531180a60fd805930acdbdb3050a00104ba7b1ac630264b8c017dd6dc01e88445b77804f6a9b6e8199959d80801b8c8c8009430796ab86800c400e9aac014acf0a910a8741617637321000) 

That's why it's important to provide a way of replicating it beforehand. Can you share a snippet where I can see this error? Thanks!

**Comment by jmkeith** [comment]
I'm having issues with the example BlobProvider and usePDF from the examples.
I've included a sandbox link
https://codesandbox.io/s/jolly-ishizaka-5e3im
