### ISSUE TITLE
usePdf hook keep showing loading state

### ISSUE THREAD

**Issue by kasugaicrow** [diegomura/react-pdf#1298]
**Describe the bug**
I'm trying to use the hook **usePdf** inside my react based electron application. I followed the example but the loading state keep staying true. I have no error in the console and I don't know how to go ahead.

**To Reproduce**
Just copy paste [this example](https://react-pdf.org/advanced#using-the-usepdf-hook) and try it inside an electron app made with electron forge, typescript and react.

**Expected behavior**
I expect the link to show up to let me download the file.

**Desktop (please complete the following information):**
 - Windows
 - Instance of chromium (electron)
 - 2.0.12

**Comment by diegomura** [comment]
I don't have an easy way of running this on an electron app right now, but just tested it on a web app and worked fine 🤔 Something I remember seeing is that sometimes electron apps run the node build of the lib instead of the web one. Please try importing from `@react-pdf/renderer/lib/react-pdf.browser.es` (or .cjs) instead. Otherwise, can you provide a small project I can download and run? That would be very helpful

**Comment by jmkeith** [comment]
I'm having issues with the example BlobProvider and usePDF from the examples.
I've included a sandbox link
https://codesandbox.io/s/jolly-ishizaka-5e3im

**Comment by Codeia** [comment]
same issue here. copy pasting the example from the documentation website - not working for me.

**Comment by tirmey** [comment]
> importing the hook from @react-pdf/renderer/lib/react-pdf.browser.cjs works for me. Thanks! 

But there´s a definitive solution to this issue?
