### ISSUE TITLE
Latest react-pdf version has problem with border/margin

### ISSUE THREAD

**Issue by tomaszzmudzinski** [diegomura/react-pdf#1299]
**Describe the bug**
When I try to use margin & border it looks like border-right and border-bottom not work as expected.

Check this REPL:
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a70e94a807a5e023755d741b356ec0806e3264018b828b2013863e49a06677824700663c8c482242005c3000e400f21000ee3c224a1100341c10cec0e11100165050000e10a1baba7e8e727cd03c5048c0b2a08cba10ba2071094aba006e008c00ccba009a00fa002a00d2006a006c20001c00ea209df200aa4abd8c43001a009c3c0082fbb2797e1164aad6b6a090b0d21810383000ca50a2184fd918184ec0aed5183e0e22854e15f269183c673b8c0e16e80019529a45338945e2c80099f2281804040222412860f2110f180006b33a5154889839d2e64001286149502e0d0ec2e162a3bc54442a1d0585d3112e4000

**Expected behavior**
It should work exactly like on raw HTML/CSS:

https://codepen.io/tomaszzmudzinski/pen/XWMWbOZ

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - React-pdf version 2.0.12

**Comment by diegomura** [comment]
It's not a bug 😅 . You cannot add `margin` to the page, since there's nothing outside of it. I guess it's a border case, and although semantically does not make sense, we can render what you would "expect", which is some sort of view inside the page. Borders [are working fine](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659da74e5401a920c01dc634009e006c33600de731440074008c4001359017c6007a21c26074a558ef0167add06cd5bb0201b8c990062e0a06804e187c48d018fe78ca1c00663c8c48f2b2005c3000e400f210923cf2ba2900341c10fec0c92900165050000e1089c6c651be9a7cd03c5048c01aa08cc610c62099d9bac6006e008c00ccc6009a00fa002a00d2a2006c20001c00ea20235a00aaba138cb3001a009c3c0082971a9551296406ee9ea090b06a1810383000ca500a181f99430183f301026d0c044383a7d32522c2460f1fcc130324c6000602b0981483e0559200562c658603a7f2e8c2a500131545032103c890ba327c878c0003583d28066c4589e1e320009430eca8170685e008b129e12a22150e82c2999e400000)

**Comment by tomaszzmudzinski** [comment]
@diegomura is it possible to add those borders for the whole page? I tried to set the height to '100%' but it's too much
