### ISSUE TITLE
Dom rendering, memory leaking issues using PDFViewer

### ISSUE THREAD

**Issue by fidaay** [diegomura/react-pdf#1326]
**To Reproduce**
I have a dinamically dom pdf rendering by order id
![image](https://user-images.githubusercontent.com/33124156/119226838-5a87b200-bac8-11eb-85c3-38794b607f90.png)

What is happening next is that the pdf is being rendered with the fetched order data
![image](https://user-images.githubusercontent.com/33124156/119226869-755a2680-bac8-11eb-8b8d-7759ac0918b2.png)

UI Example on clicking watch order
![image](https://user-images.githubusercontent.com/33124156/119226934-cf5aec00-bac8-11eb-8f94-f939c6e5dfd8.png)

I thought it was all fine until I started to notice that everytime we create a new PDF, it creates a new blob, new url and for that a new dom rendering. So, it starts to leak memory.
![image](https://user-images.githubusercontent.com/33124156/119227287-552b6700-baca-11eb-86a8-e23f69b3e30b.png)

**Expected behavior**
The expected behavior is to not leak memory. I know this problem could only be on my side, but I haven't found a solution yet. I took a shot at the usePDF hook but the problem with the hook is that it mainly function doesn't support DOM rendering.

**Screenshots**
Memory Leaking
![image](https://user-images.githubusercontent.com/33124156/119226785-1f857e80-bac8-11eb-96a1-5d1993a7b32f.png)
![image](https://user-images.githubusercontent.com/33124156/119227500-69bc2f00-bacb-11eb-85dd-746596506ca3.png)
![image](https://user-images.githubusercontent.com/33124156/119227506-717bd380-bacb-11eb-8178-895b51df754c.png)

**Desktop:**
 - OS: [Windows 10 latest version]
 - Browser [Firefox Developer Edition, Firefox, Google Chrome]
 - React-pdf version [e.g. v2.0.13]

**Comment by kidroca** [comment]
We have the same problem
A web app where you can browse a list of multiple users
When you open a user there's an option to make a pdf document with some user data
When you do this the first time the PDF is generated instantly - doesn't matter which user you start on
Then when you switch to other users and generate a PDF again it becomes slower and slower 
to the point that after 15-20 documents our app seems to hang

It's easy to recreate if you have a storybook setup with 2 PDF documents and previews
Toggling between the 2 - each time you'd see the preview takes longer and longer to render

This also happens while developing with **hot reload** - you change some Document, hot reload is triggered
the more this happens the slower the app gets

But for some reason this doesn't not happen in the REPL - no matter how many changes you do there everything
works instantly - perhaps it's because it uses `ReactPDF.render(<Quixote />);`, while for our app we have tried:  
- the `PDFViewer` component -> get's slower and slower each time
- `usePDF` or `BlobProvider` then use our own `iframe` to render the `url` -> gets slower and slower each time

---

This is what I'd see in the network tab:
![image](https://user-images.githubusercontent.com/12156624/121339910-a68b8100-c927-11eb-8b7c-68ffaa470ecc.png)

Each time I render a document it takes 3 passes 
1. our app is still fetching data and a blank document is rendered initially
2. document renders 1 time - some items still need to compute dimensions 
3. document render 2nd time - everything is as it should 

I think the problem here is that as you can see I have 97 `blob:https://` items rendered, and the blob object are still in memory as I can click on the very first request and open the link in a new tab and see the first PDF document
IMO these need to be revoked when the PdfViewer unmounts or when the `usePDF` hook gets an update or triggers a new render for some reason

**Comment by kidroca** [comment]
Here's some more info I found out while debugging `usePDF`

##### 1st pass (Empty Page)
Blob is created, there's no `previousUrl` - correct
![image](https://user-images.githubusercontent.com/12156624/121344663-b22d7680-c92c-11eb-9c55-72fb897d66e4.png)

##### 2nd pass (Partial Page)
Blob is updated, there's no `previousUrl` - incorrect - there actually is. The code doesn't try to revoke unused urls
![image](https://user-images.githubusercontent.com/12156624/121345095-1ea87580-c92d-11eb-95d5-dc7549d37955.png)

##### 3rd pass (Complete Page, final render)
Blob is updated, there's still no `previousUrl` - incorrect
![image](https://user-images.githubusercontent.com/12156624/121345214-40a1f800-c92d-11eb-9a81-262b4f30154d.png)

---

The problem is here:
https://github.com/diegomura/react-pdf/blob/9f9e37480ea3c03bb3de0d53213dfacbb49dbf79/packages/renderer/src/dom.js#L40

The code uses `state` but `state` is not listed in the `useEffect` dependencies `[]` which means it will always be the initial `state` value - even if it seems you have a closure with it
So even when `setState` triggers a state update and a rerun for the hook, the "revoke" effect doesn't perform as intended
I know you intentionally want the main `useEffect` to run only once, that's why it has no dependencies - to have a reference to the  **current** state you can use `setState` with a callback which would give you the **current** state

You don't need this effect IMO 
https://github.com/diegomura/react-pdf/blob/9f9e37480ea3c03bb3de0d53213dfacbb49dbf79/packages/renderer/src/dom.js#L62-L65

The call to `setState` can be changed like so:

```js
    const onRenderSuccessful = blob => setState(prevState => {
        if (prevState.url) URL.revokeObjectUrl(prevState.url);

        return {
          blob,
          error: null,
          loading: false,
          url: URL.createObjectURL(blob),
        };
    };
```

Or an alternative is a cleanup effect like this:

```js
useEffect(() => {
  // returns a "cleanup" function
  return () => {
     if (state.url) => URL.revokeObjectUrl(state.url)
  }
}, [state.url])
```

Since the above happens in the "cleanup" of the `useEffect` - `state.url` will always be the last value prior the current value
e.g. when the url is "blob:abc" and updates to "blob:bcd" the new `useEffect` run get's "blob:bcd", but the old `useEffect` runs the cleanup with the previous value "blob:abc"

---

Also I think the main `useEffect` cleanup should also revoke the URL - think about it - where's is that hook used - inside a component of course, when would this "main" useEffect cleanup run - when the component unmounts
And since the component that used the blob and the url is no longer mounted nothing is using them anymore

Even if they are rendered/opened somewhere e.g. a new tab - they will remain rendered
When you revoke a URL that's already opened somewhere it's stays loaded on screen - but it's no longer
possible to load it again which I think is OK for this case

Here are some examples:

I have a button component with a download link 
  - it uses `usePDF` to make a downloadable PDF file 
  - I can only download the file while the button is mounted
  - I don't need the blob or the url when it unmounts

I have a PDF preview 
  - it uses `usePDF` to show a Document
  - I can only view the document while the PDF Preview is mounted
  - I don't need the blob or the url when it unmounts

I have a web page component
 - it uses the `usePDF` to get a blob and a url
 - it renders a preview for the url
 - it renders a download link with the url
 - this web page component unmounts - I don't need the url and the blob

---

I can submit a PR for the above

**Comment by Yuri-Ribeiro** [comment]
@diegomura, first, congratulations for the excellent work.

I am facing the same issue mentioned in this topic. With each new rendering with PDFViewer, the time increases, as well as the amount of memory used.

I did a test by monitoring the function assigned to the _onRender_ of _Document_ component. And, even if PDFViewer is unmounted from the page, or even its parent is unmounted, onRender continues to invoke for all documents already generated when there are new renderings.

I believe that the solution proposed by @kidroca is promising.

Waiting for some update regarding this bug. Thanks.

**Comment by redaben** [comment]
@fidaay : did you implement @kidroca solution or you found something else ?
@kidroca : did you add the cleanup effect or are you waiting for the PR approval by @diegomura ?

**Comment by kidroca** [comment]
I'm planning on submitting a PR next week 

There might be a bit more to it, judging by 
> I did a test by monitoring the function assigned to the onRender of Document component. And, even if PDFViewer is unmounted from the page, or even its parent is unmounted, onRender continues to invoke for all documents already generated when there are new renderings.

This sounds like something different from the URL blobs issue I've described 

I'll try to track it down as well

**Comment by kidroca** [comment]
I've submitted a PR regarding the Object URL cleaning
I does release the urls as originally intended, but does not fix this issue

The issue still exists when you switch between 2 documents, each new render becomes slower and slower even though nothing else changes

>  onRender continues to invoke for all documents already generated when there are new renderings.

Looks like this is the main cause

I have one Document that uses SVG and another that doesn't, and when I move to the the other document I still see SVG related warnings like _"SVG node of type DEFS is not currenty supported"_ while I'm rendering a document that does not contain any SVGs

**Comment by kidroca** [comment]
Found the real issue and added a patch to my PR

The `pdf` handler here is a singleton and the change handlers added here weren't getting cleared when we're done with the hook:

https://github.com/diegomura/react-pdf/blob/9f9e37480ea3c03bb3de0d53213dfacbb49dbf79/packages/renderer/src/dom.js#L50-L51

That's why _"onRender continues to invoke for all documents already generated when there are new renderings."_

Updated the hook cleanup to also remove the `change` handler and verified that I can no longer re-create the issue, switching between different documents runs very fast

**Comment by fidaay** [comment]
@redaben I'm sorry, I didn't pay too much attention to kidroca's, but I can assure that this problem is something that is not a simple thing to solve. I've found the "solution" and the real problem by just testing this package on another component.

So, in order to update your component and re-render without having useEffect issues, you have to handle it in the same parent component. Instead of "destroy" and "build" again your PDFViewer component you just re-render it. 

If you see my handleCardBack function in the pictures what it does is that it set to false the viewOrderPDF hook, and it just unmounts the PDFViewer child component and there is where the problem start.

So who knows, maybe someone with extra-time can solve this problem, but that's the solution I'm taking for now.

I'm closing this issue too because I've found my own solution.

**Comment by kidroca** [comment]
> @redaben I'm sorry, I didn't pay too much attention to kidroca's, but I can assure that this problem is something that is not a simple thing to solve. I've found the "solution" and the real problem by just testing this package on another component.

Actually it was quite simple to solve, once properly debugged and traced, it was just a missed event listener cleanup

You've found a workaround to reduce re-mounts it might work for you, but let's say you use the `PDFViewer` on a specific page, each time you visit this page it will make rendering slower and slower as nothing is clearing the events listeners attached from the previous visit

You can try the fix yourself, by replacing this in `package.json` 

```jso
 "@react-pdf/renderer": "https://gitpkg.now.sh/kidroca/react-pdf/packages/renderer?2fa4df0056a7c7c1dda69538e2ab8a874b1a5d5b",
```

your original source that conditionally mounts the viewer, should work without problems

**Comment by Yuri-Ribeiro** [comment]
@diegomura it really seems that @kidroca 's solution is the definitive one. Could you analyze the PR he submitted? Congratulations to everyone for their efforts!

**Comment by redaben** [comment]
@kidroca well done !! You rock ✊ Can't wait for @diegomura to review your PR !
