### ISSUE TITLE
FlexWrap doesn't work

### ISSUE THREAD

**Issue by duyank** [diegomura/react-pdf#1353]
**Describe the bug**
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed38c0e9aa8035241803b8c69e224480666250d24009c3302849c002e00e476421f700686001582341205908030b8262b2b8c3b8400038f3006002d3c861421860b1f8c15860a003a9d8f026c7ba1a9427baabab6a700241e81a186a68755000aa15b14000592040c10cc282b0b2c00232c8c00e8e8f8f474ecfcf0e2d464cc0cdce0faf0d2d6ced5003d0f4a1b034e89fe91bb66b36df1a9a4a5b5803897a1ac54ffbcb2401acf85e04180949111080ec15071296af50ea75ce7d3d88c0e9b560c0004cbb05ba22698ac69d91f74e8dd5aa4ca29c9e94ea3224c50511994c722480800724c0c9d95430071823076491e0243036461398c6e7f8a0e81e089780261aa888d8521e0ae9c00018004824e2c97737927181eb65507962a30105516b35045e4595018250c04ea4d395bdaa73a03198ac7601000dc6432000c4a2b2071f086983b08a38161e23090222105400f210433cae1be0e040ecc00abf4a050048415c2713858a2723e34078ce602c9408c138404e206cee64e003729801984e004d003e97400d2ba001b080001c45101f7e400552520f186380068013878004103ec8cb16771905521b238da00ca670d700065465891ffd1c9415b0e26c601394450a8b10480d1244a128481807c174203943020e002b3e69a281e06410010ba0b2a30b10ce884813c181105f00004942480005e513cab1021484c0aa1d1ce140621010d2d6ac23e14460b1162000b1d1942601701e221207c180150a4131d87e1b151186c9aa6e99c4598e6221c21c0311c0f00800c50ab19a3b150271e4771db162025ccbd089624497114971ac99a2303c1d8319801859620361302f100031d15a65010020f21312c4c0c0619510996654cf3a592e5b9104fc165c9ac029299a6998f6ea79e941055645c06670497b9a9659466c53f3f10d109500d9e245441084611399c119995291517448330102a40012b793c180f97d1745f5fc19951695ae7b9ba20acdb51db1e1ce7cd1069176051544883f1f901669747be0460a256505557115434654419e5613c61d9a3d58d5d9ee03982bb59428090b427130218108ed615069726764520776483386e1c43c3c810080222e91817df90c557799966285e4f98393d9c18816140b10139436d7c296a4e592f6894d7d99327d964fdfa7fd0e103817e697a8683460c91405c0d0619462c128829e054220a83a0583bac19904000

**Expected behavior**
`this is content 2` will be wrapped to newline (same as the browser)

**Screenshots**
![image](https://user-images.githubusercontent.com/19285404/120577184-290ad100-c44e-11eb-89a6-bfc4842b3bb9.png)

**Comment by diegomura** [comment]
FlexWrap does work. Rendering text on variable flex container such as what you are doing there however is tricky. For text, we need to know the width of it's container in order to layout the glyphs and know where to break lines. At the same time, those flex containers depend on each other's widths to layout, which depends on the text length... and so on. The only solution in these cases when working with text that wrap is defining their width (with fixed units or percentage), such as [this](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed38c0e9aa8035241803b8c69e224480666250d24009c3302849c002e00e476421f700686001582341205908030b8262b2b8c3b8400038f3006002d3c861421860b1f8c15860a003a9d8f026c7ba1a9427baabab6a700241e81b1a9a4848c21921294000585400b000300293b8c1d46a68cd5000aa15b3f52040c0acc282b0b2c00232c8c32eafae6f46efee1daeac9f6cc1ec1df7af1d44dddd5003d02ca1b034e9bfe91b4d34cd7f9b4a0a233275e4c900359f0bc08301292222101d82a0e251e5babd01bb8001c635abd466b34f92c1e472bb3d583000133dd1e54ad8d369ef32603667f5687328ef104f21aef5e009a6ef3a03198ac7601000dc6432000c4a2b2071f056983b1e0241c0b0f11848111082a00790821878224c6f838103b3002a7d281401210571bcde16289c8f8d01e33980b250230de1037880cd16a51bc006e3b00331bc009a007d39801a5740036101e28a2068fc800aa4a38e3193000d00270f0008235d913a2cee322a965f2cdb404c60990e06000656ec60fb7d1c941030e3f460b51c450a962dacd124944a24180f873103946071802b35b173c65eaef8002174140408c58a66f70d25caed7000954520005e510b6c577fbc98ff9c50311e70693d560fb37c30589694187f4a1302f86b110903e0c00a8522d8ec3f180a88153d40d234e2535cd4b59b4a1541fc78041fa54480cd040a80c0d7c20db9691820e45810a4250b88d08d530cd1181e0ec354c033c9d4bd621187f3226d041e47fd00980174e0e8862989d8f156204a135758876162b0d6070fd50d134236223869360c5868ce0b4e1374fd368a8954dd3a0868e0a8038e422a20842308f8e53b0dc24cb88e62419808152000952f1e0c01237f0e1c2fe098a53283b3575d0303b1fd4fd6e5bdf8c1384e7cec37c3f11174e19862927f11d0f6ca6cca054f021ccd28ad5d448bcaf3a5aaf73d8c43bcee3b66ca02ca140144d1388e10c08400b2c9809201000392603249ad285bc32419c370e21e1e408040111288c146fc99c96b98d6314313bab8d7acd0c40b0a05881ece14abe11d57b588f2bcae3dc1e246d63c6ea2a6871669aa5b36cc828a30648a02e06805455160946caf02a110541d02c0de620db200000)
