### ISSUE TITLE
Feature request: Caching, or cached attribute, similar to fixed

### ISSUE THREAD

**Issue by danomatic** [diegomura/react-pdf#1365]
I have a scenario for caching that I think would be a massive improvement to performance.

I am creating a large PDF of letters for print that repeats a <Page> component like so:

```
const logo = 'myLogo.png';
const body = 'Dear customer, this is a letter to you that is 2 pages...';

<Document>
  {recipients. map((recipient) => {
    <Page wrap>

      <Image src={logo} />

      <Text>{recipient.address}</Text>

      <View>{body}</View>

    </Page>
  })}
</Document>
```

PROBLEM
Because the content of `<Image src={logo} />` and `<View>{body}</View>` never changes, I believe it would significantly speed up rendering to add `fixed` to them. The problem is that the `body` text is long and results in each recipient getting 2 pages, and I don't want the logo or body to repeat if the body overflows to a second page.

PROPOSED SOLUTION
I would like a way to have `cached` or `fixed` content that only repeats once for each instance of `<Page>`, regardless of wrapping. Perhaps you could just add render caching for scenarios like this, but perhaps a `cached` or `static` attribute would be needed to indicate that the content is static. What do you think?  Is there already a way to achieve this?

I'm hoping that the existing code for `fixed` could be leveraged for this pretty easily, but I'm not familiar enough with the source to know.

I would be willing to donate a small sum of money if it helps get something like this in place. As it stands. react-pdf takes about 250ms to render the letter for each recipient, and I'd like to optimize it as much as possible, because I am creating documents that could have 100s or 1000s of recipients.

**Comment by diegomura** [comment]
Hi! Thanks for taking the time to write this feature request. Super helpful. 

Images are being cached already internally. So it's only fetched once. But text don't.

Reusing `fixed` might be confusing since the current usage is unrelated to this. Just means that the component should be rendered in all pages. This is the sort of things that I think can be solved transparently for the user without it having to define a special prop. On text rendering there are already a lot of things being cached. Succesive text renderizations are actually very efficient. Maybe we can create an internal cache for `string text -> glyphs`. This needs to happen internally, since text layout not only depends on the text and attributes but also on the container it's being rendered to.

I must say though, that based on what you describe about your document, I'm pretty sure most of the perf price it's being payed on the pagination step. Unfortunately pagination is somehow a N^2 order (not exactly, but not linear either). It is so hard to fix that part. since in order to guarantee all cases will work the page needs to be relayout after it breaks
