### ISSUE TITLE
render graph in my document

### ISSUE THREAD

**Issue by GusMartins499** [diegomura/react-pdf#1422]
Hi guys, how's it going ?
Somebody have an example of, how to render a graph in PDF ?
I'm not fluent english, so, perphaps i don't understant all in forums
I try to reproduce this: https://stackoverflow.com/questions/45086005/recharts-component-to-png. But, i was not successful :(

My goal is: 
1 - Generate any graph using recharts (https://recharts.org/en-US/examples) or, another lib to make a graph
2 - Get this graph and render in my document

Thank so much for any help

**Comment by michaelmarziani** [comment]
@GusMartins499 Hi Gus,

I need more information in order to help you. For your goals, goal 1 is out of the scope of this library and this Issues forum. Once you have a graph in the form of an image ([PNG, JPG, base64 image string](https://react-pdf.org/components#image) or [SVG](https://react-pdf.org/svg)), refer to the documentation I linked.

If you have a question about the documentation or a code sample, please let me know. Another helpful resource for testing react-pdf code is the [playground / REPL](https://react-pdf.org/repl). Good luck!

**Comment by diegomura** [comment]
Thanks @michaelmarziani for answering this thread. Indeed, the solution here would be using the built-in SVG primitives. I've seen people using graphs from recharts converted to react-pdf (although I'm not sure there's an abstraction to it), but in theory any svg file should be possible to convert to react-pdf SVG's primitives. Closing this as answered but please reply if we missed something
