### ISSUE TITLE
Render a fixed, absolutely positioned footer only on the last page

### ISSUE THREAD

**Issue by michaelmarziani** [diegomura/react-pdf#1424]
I am creating an invoice with dynamic data, so I don't know in advance how many pages will be generated. On the last page only, I want to place a footer at the bottom which contains payment information and the total amount.

I've tried rendering the footer using ```<Text>``` and a custom render function which detects when ```pageNumber``` is equal to ```totalPages```. This correctly displays only on the last page, but it removes much of the formatting, borders, etc, and no longer looks consistent with the style of the rest of the invoice.

A solution that I think would work quite well and enable other use cases would be to make ```totalPages``` available in the render function for ```<View>``` as it is in ```<Text>```.

Are there any other ways I might go about this? I'm still learning the package so perhaps I'm missing something.

**Comment by michaelmarziani** [comment]
@diegomura I'm willing to try to write this feature myself (i.e. access ```totalPages``` in ```<View>```) if you could help point me in the right direction.

I cloned the repo and searched for totalPages. I can see I'll need to add ```totalPages``` to ```ViewProps``` under ```render```. Could you point me in the right direction as to what would need to be done afterward? Are there parts of ```<Text>``` I could use as a template?

**Comment by diegomura** [comment]
> A solution that I think would work quite well and enable other use cases would be to make totalPages available in the render function for <View> as it is in <Text>.

Unfortunately this is not as simple as it sounds. You cannot have `totalPages` ahead of time since this is a result of the actual layout process. The way the `render` prop works is by triggering another layout, but this can affect the `totalPages` and `pageNumber` on the render component, creating an unwanted result, and this can repeat.

In this case though, I don't see why you would need something like this. Cannot you add the footer as the last component of your document? that way it will render in the last page.. If you need it to be at the bottom of the page absolute position should still work (haven't tested it though), or maybe using flexbox can also be achieved

**Comment by michaelmarziani** [comment]
Hey @diegomura, thanks for your thoughts and thank you for the wonderful library.

I had tried using flexbox and absolute positioning but wasn't able to make it work at first. I just gave it another go and got it working with absolute positioning. In case anyone else is having trouble doing this, here's the style for the ```<View>``` that wraps my footer:
```jsx
  footer: {
    bottom: '10pt',
    left: 0,
    position: 'absolute',
    right: 0,
  },
```

Closing this, thanks again @diegomura!
