### ISSUE TITLE
CSP Violation for dependency Restructure/src/Pointer.js:line 229

### ISSUE THREAD

**Issue by djaffer** [diegomura/react-pdf#1451]
I am not able to use strict CSP without unsafe-eval. Can you please fix the dependency being used?

![image](https://user-images.githubusercontent.com/5740725/128815477-a3bd9ad6-8503-451b-8a4a-4274ca877c44.png)

![image](https://user-images.githubusercontent.com/5740725/128815596-846e8b1c-55df-4f45-90f9-4d84dd267663.png)

**Comment by jeetiss** [comment]
@diegomura maybe it's time to update `Restructure`? I can setup babel for transpiling this package to es5, as I understand only this blocks for update!

**Comment by diegomura** [comment]
That sounds good! I'm not familiarized with what's needed. Seems you have a clearer idea so I'll trust you 😄

**Comment by djaffer** [comment]
any update on this please

**Comment by jeetiss** [comment]
@djaffer my plan doesn't help with CSP because `@react-pdf` has another eval in `@react-pdf/yoga` and it's not so easy to fix `eval` in it. you can read more at https://github.com/diegomura/react-pdf/issues/510

P.S I'm still planning to upgrade `Restructure` to the latest version because it doesn't use an obsolete buffer constructor. I will do it when PR https://github.com/diegomura/react-pdf/pull/1609 is merged

**Comment by twistedpair** [comment]
Looks like #1609 has been successfully merged. Any movement on addressing these CSP blocking issues? Thanks.

**Comment by jacek-seliga-fat-ninja** [comment]
+1 on this @diegomura

**Comment by maelgff** [comment]
+ 1 on this 🙏

**Comment by djaffer** [comment]
Is this fixed merged to recent release?

**Comment by jepek** [comment]
Hi @diegomura,

Same question from me - [has version bump up for reconstruct package in the fontkit already been released](https://github.com/carlobeltrame/react-pdf/commit/955bac4e8110d88a14bcb0a6b17d07201e2077e6)? 

Without it, I have a problem with the CSP strict rules and I cannot use your great package in production.

Thank you for your work!
