### ISSUE TITLE
Style typing is wrong for the display property for the View component

### ISSUE THREAD

**Issue by barcern** [diegomura/react-pdf#1635]
**Describe the bug**
When adding styles to a view, the full options detailed in https://developer.mozilla.org/en-US/docs/Web/CSS/display are not supported.
I'm looking to add `display: table` to my `View`

**Expected behavior**
`display: table` is an accepted property for `View`

**Screenshots**
![image](https://user-images.githubusercontent.com/16946845/144897166-898cb6a0-e7ca-45f0-a7b0-807ac639df93.png)
![image](https://user-images.githubusercontent.com/16946845/144897211-d4a2c102-9fe5-49c3-9e40-984c2a3d2be8.png)

**Comment by jeetiss** [comment]
style types is not wrong. `@react-pdf/renderer` doesn't  support `display: table` and any other display types. it supports only flex.

`@react-pdf` works without browser, but mimics browser api. flexboxes are emulated by [yoga](https://yogalayout.com/) and nothing more. 

that's why style types have only `flex`.
