### ISSUE TITLE
Rupees Symbol coming as text " 1 "

### ISSUE THREAD

**Issue by devamiya** [diegomura/react-pdf#1643]
When using the rupees symbol i.e. INR it's converting it to the "1" 

<img width="226" alt="Screenshot 2021-12-15 at 1 28 55 AM" src="https://user-images.githubusercontent.com/42324072/146070736-2ffbac80-1a4c-4234-b304-f22083bce8f8.png">

**Comment by Nishanth15** [comment]
Hi @devamiya, could you find any solution for this issue?

**Comment by krushna-cruxbyte** [comment]
Facing same issue. Any help will be appreciated.

**Comment by kotesh-arya** [comment]
**Possible reason:** Due to the pdf render not being able to process the font type of the Indian rupee, a supported font family should be provided to render the character.
- To fix this, you can [download](https://fonts.google.com/noto/specimen/Noto+Sans) **Notosans** font zip file and extract it in your project's `/src/fonts` folder, then import and use it.
- Inside the document body just copy paste the rupee sign  ₹

``` 
import NotoSans from "../fonts/Noto_Sans/static/NotoSans_Condensed-Bold.ttf";

Font.register({
  family: "NotoSans",
  src: NotoSans,
});
const styles = StyleSheet.create({
  page: {
    display: "flex",
    /// remaining styles of the document
 ```

**Comment by omzi** [comment]
I had the same issue with the Naira sign (₦) getting rendered as "¦".

In addition to what @kotesh-arya said, you basically need a font that is known to have good Unicode support, such as Arial Unicode or Noto Sans. These fonts are freely available on [Online Web Fonts](https://www.onlinewebfonts.com/fonts).

Cheers.

**Comment by diegomura** [comment]
You need to setup a custom font for special symbols. Default fonts just contains a limited set of chars
