### ISSUE TITLE
Incomplete or corrupt PNG file

### ISSUE THREAD

**Issue by pocockn** [diegomura/react-pdf#1747]
I am having problems adding an image to my PDF.

I keep getting the error:

`Incomplete or corrupt PNG file`

The image displays fine in other parts of my app. 

I am using

```
<Image
    src={`data:image/png;base64,${file?.base64}`}
/>
```
I can see by console logging that the correct base64 value is being returned from the API I'm pulling the image from with:

```
const resourceFiles = async ({ data = [], identityAccessKey, resourceID }) => {
  const resourceFilesWithBase64 = await Promise.all(
    data.map(async (file) => {
      const response = await fetch('/api/getIdentityResourceFileById', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ fileID: file?.id, identityAccessKey, resourceID })
      });
      const fileContent = await response.json();
      return {...file, base64: fileContent?.base64};
    })
  );
  return resourceFilesWithBase64;
};

export default resourceFiles;
```

The error seems to be in `fetchimage.js`

<img width="966" alt="Screen Shot 2022-03-12 at 00 07 50" src="https://user-images.githubusercontent.com/6921933/157986417-c72ef1c4-923d-4bf1-939b-9b3375a6721c.png">

Has anyone encountered this before?

**Comment by lmargules0866** [comment]
Bump on this issue. Having the same error with the console outputting the "Incomplete or corrupt PNG File" warning. Line 77 in fetchImage.js is also referenced for my error. 

I am using base64 images and using that as the src.

Is there some sort of file size limit I'm not aware of?

**Comment by lmargules0866** [comment]
@pocockn I have solved the issue on my end.

It came down to the image incorrectly trying to render as a PNG based on the base64 image prefix.

Above, it looks like you have:

`'data:image/png;base64,'`

hardcoded into your src. This is a problem because what if the image is a different type? 

I had to approach this with a messy solution on my end. 

I first split the base64 image data on the comma. I then wrote a helper method to construct the 'data:image/[TYPE];base64,' prefix based on the magic number of the image data. If the magic number is /9j/ then it is a JPEG. If it is an 'i' then it is a PNG and so forth.

**Comment by pocockn** [comment]
Hey @lmargules0866 , turns out it was due to the API I'm pinging returning either a JPEG or PNG.

I took some inspiration from your magic number tips and got it working for both types.

Thanks

**Comment by diegomura** [comment]
Seems resolved

**Comment by OtacilioN** [comment]
I had the same issue, my file was saved on s3 as png but actually was a JPEG.

but the first character of the base64 defines the type, "/" for jpg and "i" for png.

````
const firstChar = base64img.charAt(0);
  const extension = {
    "/": "jpeg",
    i: "png",
    R: "gif",
    U: "webp",
  }[firstChar];
   return `data:image/${extension};base64,${base64img}`;
  `````
