### ISSUE TITLE
Texts rendered on top of each other if they have "flex: 1" style

### ISSUE THREAD

**Issue by kissthom** [diegomura/react-pdf#1762]
**Describe the bug**
After updating to version 2.0.21 some of our PDF-s are broken. If we want to render multiple Flexboxes with column direction under each other they get rendered on top of each other. It seems to have something with the {flex: 1} style of the Text-s in the View-s which seems to cause the issue with the rendering. 

**To Reproduce**
[Example on Codesandbox](https://codesandbox.io/s/react-pdf-flex-1-issue-ygj7uw?file=/src/App.js)

In this codesandbox repo you can find a working document and a broken one.
If you switch the version to 2.0.20 both documents are working well. 

**Expected behavior**
The texts should be rendered under each other.

It should look like this:
<img width="336" alt="react-pdf-texts-overlapping-working" src="https://user-images.githubusercontent.com/6662590/160599364-138b7265-eec5-4c19-b454-7c5aba3ed998.png">

But it looks like this:
<img width="412" alt="react-pdf-texts-overlapping-broken" src="https://user-images.githubusercontent.com/6662590/160599450-d803959e-4883-4cd7-aa1b-51ec2303ff94.png">

**Versions**
Working with:  React-pdf version 2.0.20
Not working with: React-pdf version 2.0.21

**Comment by jeetiss** [comment]
@n-glaz this is happening because `flex: 1` expands to `flex: 1 1 0` but should be `flex: 1 1 auto`. I tried to fix it, but this change is breaking all layouts and should be released in a major update



[repl](https://react-pdf-repl.vercel.app/?gz_code=eJzFU01PwkAQvfMrJj0BKSw1Rg1fEUPwZDSiJHJi005xk3a32Z0K2PS_uws0YDxojIbT9r2-mXkzuyPSTGmCAp5wTT488CX6MBO48mGswjxFadmJkgQlxFql4F1r5CG1sihmGmWEGrXXq9Wcpq1xKQyhrhc1gJinItl0wbvPUMKUS-P5ljY6tNwrUWa6jMU2zLSXhjiJsB2qlBmmrN5YOXsLLlmK6dULvzXB2cWdmGc3o9bzZDbvYJsotvnKhq2N620TEcY8TwjqDRgMwVnQSLmWULefAP2qITC0SXBQFOCqT77ahLIcbkNskJsIGPGOA2907lW0_eGGdIB74pA6EiZLuMsbJ7j2fHDHWGgMSShp6VAleSqPa-3zuJs4smjDrDqAAHhOaqufCG0IHtWqz5z4kwt2Ql9TDJWMfmaswv8_0II1q6dhgBQsdtad884Cmqz8vs3gZFP_K_O_uZoKuRXYoT6rdshhu3plr_YB1y88Dg&modules=true)

**Comment by edenilsonfe** [comment]
I have a similar issue with this overlapping:
![image](https://user-images.githubusercontent.com/10874292/233463749-b5ff9650-0447-4594-b1a8-a871fa3f63f4.png)

sometimes the section overlap the other one. the code and style are exactly the same(I created a component for this). 

please let me know if u guys have any suggestion cc @jeetiss @n-glaz

**Comment by diegomura** [comment]
Tested reprod case. It works as expected now. Will close
