### ISSUE TITLE
Project scope

### ISSUE THREAD

**Issue by jacobp100** [diegomura/react-pdf#209]
Hey, I just saw this project - really cool! I'm doing really similar things over at [react-image-export](https://github.com/jacobp100/react-image-export). It's early stages, but I'm working on SVG and canvas export (among React Native specific stuff).

We're both using Yoga, have very similar components and styling. Your reconciler is really cool - I definitely want to do something like this.

Do you reckon there's some overlap where we might want to share packages? Not looking to do anything major now, just wanted to know what you thought!

**Comment by diegomura** [comment]
Hey @jacobp100 !
It's great you are interested in renderers.
I don't truly see the overlap in here, rather than they both use Yoga. To be honest, I don't see myself breaking this project into more packages for the moment. Not unless it gets mandatory for some reason in the future. But I'm more than happy to help in anything you might need.
