### ISSUE TITLE
Implement Goto links ( ref links )

### ISSUE THREAD

**Issue by crubier** [diegomura/react-pdf#212]
Hi, I saw that pdf kit supports setting « goto » références and inks to these references. This feature would be very useful for react pdf. The lack of this feature is actually quite blocking for us at the moment. Thank you very much for the good work !

**Comment by diegomura** [comment]
Hi @crubier !
Thanks for reporting this.
I think this is not a huge feature, and I might be able to work on it in these days. I imagine something like this:

```jsx
<Link src={{ page: 5 }}>Click me</Link>
```

What do you think?
This API enables us to extend this functionality in the future if we want to. 
Let me know your thoughts!

**Comment by crubier** [comment]
I think we need to have something a bit closer to the pdf kit api, which allows to add names anchors (or refs) in the document, and add links to these refs. This allows to provide links to precise elements whose page might be unknown (due to page wrap for example)

**Comment by mike-down** [comment]
Hi @diegomura 
thank you for the quick respond 
I think it will be more simple and natural. like this :
```html
<Link src={5}>Click me</Link>
```
if `src` is a number then we can say it's a page number.

**Comment by diegomura** [comment]
Good point @crubier . I didn't know that pdfkit enables you to do that.
Either way, accepting an object as `src` will enable to link to a page number (maybe we should call it `pageNumber` instead of  just `page`), or a particular `ref` inside the document. 
Implementing refs might be a bit more difficult (all depends on what pdfkit already does) than just linking to a page number.

@mike-down I don't find passing just the page number more natural 🤔 . It's not clear at a first glance what are you trying to link. We can support this however (accepting string, number and an object), but I wouldn't promote this as the official API.

**Comment by diegomura** [comment]
I was looking at `pdfkit` code, and I couldn't find any hint that linking by ref internally is doable: https://github.com/devongovett/pdfkit/blob/master/lib/mixins/annotations.coffee#L28

It seems to me that we can link to a page number, or a URI. Am I missing something @crubier ?

**Comment by javierfernandes** [comment]
Hi guys, 

I guess that this PR needs to be merged in pdfkit to build some "reactish" support on top of it.
Right ?

https://github.com/devongovett/pdfkit/pull/720

Seems like they call them "named destinations" in pdf (I'm not an expert pdf format :P)

Cheers

**Comment by sanohin** [comment]
@diegomura  What do you think about switching to pdfkit fork to make this feature possible to implement? seems like the main repo isn't actively maintained

**Comment by diegomura** [comment]
We already have a fork that we are using in this project: https://github.com/react-pdf/pdfkit
We should add that functionality there, but unfortunately I don't have enough time just yet. Contributions would be much appreciated it

**Comment by CodeWitchBella** [comment]
Looks like support for this was merged in pdfkit upstream https://github.com/foliojs/pdfkit/pull/947

**Comment by skjo0c** [comment]
@CodeWitchBella how do we use it from our react-pdf?

**Comment by CodeWitchBella** [comment]
@skjo0c as far as I know you don't. But having this method in pdfkit means that it should be easier to implement in react-pdf.

**Comment by DeviousM** [comment]
Did anything move on with that feature? It would be super useful in the stuff I'm currently building.

**Comment by DeviousM** [comment]
Also - currently you can define the link to the page if instead of URL in the `src` field you provide the number of the page, but it doesn't seem to work when trying to link to not-yet-rendered pages (i.e. linking from page 5 to page 10), because pdfkit doesn't seem to get that you might already know to which page you'd like to link and throws an error. Is there a maybe a good way to do that?

**Comment by RuslanNikolov** [comment]
@diegomura, could there be any solution to the last comment of @DeviousM ?

**Comment by diegomura** [comment]
Interesting... What I think it can be done to solve that is rendering links at last. Didn't know about that about pdfkit. In the v2.0 version I started it would be even easier to implement, but unfortunately I couldn't wrap it up yet. The only remaining step to build there is pagination, although is also the most hard to implement
