### ISSUE TITLE
Unexpected pdf result when reordering array items using jotai

### ISSUE THREAD

**Issue by azmy60** [diegomura/react-pdf#2371]
**Describe the bug**
I have some elements that are generated from an array, and I can re-order the elements in run time. I used the `usePDF` API and it didn't render the PDF correctly after re-ordering an array in state 🤔. Everything else like updating item's value seems to work well.

**To Reproduce**
I made the [demo](https://codesandbox.io/s/relaxed-shape-j2vqk4?file=/src/App.js) in codesandbox.
1. click the arrow to reorder the letter 'a'.
![image](https://github.com/diegomura/react-pdf/assets/38707148/dd0f54f9-d188-4e2c-9fdf-9041f6e3f8bf)
2. open the pdf
![image](https://github.com/diegomura/react-pdf/assets/38707148/21156d81-004c-4491-bbff-656f9d235336)

**Expected behavior**
It shouldn't clone the elements and should render correctly.

 - OS: Windows
 - Browser chrome
 - React-pdf version 3.1.9
 - jotai 2.2.2

**Note**
For now, I could fix this by refreshing the whole component that uses `usePDF`. See my implementation in the demo.

**Comment by KN3LL2K** [comment]
I had a similar issue and its something to do with the keys in the .map.

If i make this change to your codesandbox, it works:
```
{items.map((item, index) => (
  <Text key={`item-${item}-${index}`}>{item}</Text>
))}
```

**Comment by diegomura** [comment]
Yes. Keys needs to be privided, as you would do with plain React

**Comment by Legsleg** [comment]
@diegomura 

Just ran into the same problem - react-pdf fails to render correctly, when the same key is used for the same content, but at a different position. Plain React manages to deal with that just fine. In fact, as I understand it, that is the main idea behind the key prop. Helping React keep track of where some specific element moved within an array. By keeping a unique key constant as an identifier for potentially neither unique nor constant content. Enabling for example keeping the currently selected input in an array of input fields selected even when reodering.

The solution by @KN3LL2K explicitely violates this idea by making the key not only depend on a unique identifier (item) but also its position (index). So if the position in the array changes, the key changes. This approach solved my problem with react-pdf too.

I think this is fine for what react-pdf does, but it probably should be mentioned somewhere. Otherwise this definitely feels like a bug since it does not match plain React behaviour.
