### ISSUE TITLE
Support CSS Word break

### ISSUE THREAD

**Issue by antonin-arquey** [diegomura/react-pdf#248]
**OS:** Linux 4.13.0-45-generic

**React-pdf version:** 0.7.6

**Description:**
The css [word-break](https://www.w3schools.com/cssref/css3_pr_word-break.asp) property does not work.

**How to replicate issue including code snippet (if applies):**

http://i.imgur.com/9LBq4um.png

REPL : [REPL example](http://react-pdf.diegomura.com/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618a012ca1402e185b66c02db50a01cc3983e0098003001a5682019b828583802f643202b22c1ed9000f28010510731526007260c8c1d0ab60e08046d58006b31144002b9800098030882208051f2d803132000b22626b929b1d298008b228052d07380c507072052598322a618654000a9e642a8510914003ab69703504255b802f9bbb88307c1f008a8a318038bf803b9f00233f5b9cd8da4c32a4ccc83ccc12fae6c9a647153027215d9cd54c00d2bba44f9ae1a1f4eadef2d28d53c4c9b6eec0331b8d8b328b040042546a37862ee4877800b4d444221aec2510486c0b051296e6c65071910b6f9e2b66f69102609e1f1f9022170a45a2767882c120969001d9aeb88d81310d26246d493b19052a9be7f315e95118bc4006cb2f6749825cb73e391ff014bcfe22f598a699288b4a99c8764003965ff690aa946ac40253542ddb93755e716d2c286c65c590d20027321fe9c8f9f40094006e6624740905830440c00c0c1e84a000f265e30121238a0003e758a6000ad431320e05a643a000446604a5660510e367f2e02ae21a821081743a95bce18d829800ca49bceb4302050e84638f50a44e371907d51e082014601560850282b4203c003d2ee67b30e378381d60871a8a428989774793eee07516410800faa7882672b4bdedf6d88faa1083000092dba664b8a60fb0e3fa18298006a8dacc702e01394ec84ce4308c7d3417d9c1085217824ed3840a41cc5852e306d4262c0d3a1168711351f430094ee004621e6c8328c8010ca004440f1043680132802720bc4f15a1f10126844070427209a328c2668b2471013c9dc549927c9ca2686a469da069e460810651a6361bf8a6a6751686d1783d154591bfafeffb3e303be999319e996b035059940f20c0d18f4670900105030350e7ab41c0401c3009218830320963f93d30471b20b24404230c74108ad036603c5e7b044114001370d410c5409071832cfb1660350488700023804d4000aab02381c10846618914c0422487d4c0001baf5be405ed4c5301802034014004c1125c62745c336600c001322be680301b6d55cd600c51c0ed5000d820b5b36b46b525d420520108395c64f640c83b5b429030264011cdd4055a589c61696755446e580575b0542b454110212945c24313444012b4502d0a5a4d29525100f4816f299a905749954799c66eef0720b3053fdb53884d1a85d9244ec8e539f4de14cd11a42dad2231bb9d3c6559f84a13cc3142e182e601ee601e0f85b14f97e405414e474395e1645a799df1580897255c00569679d0d25596bd463e510e48c5470a55381761d5553e496c69ea96223588f4dd1d4fddd525a77f51ce0dab48d81c4d53508337fd6802d4b4ad6b46d98f9cdb6ed6d9080751d0dac76745da6cfba7bdd3413d2f70c203bd3d17d642fd31c4540db9cb5509e43290e9bb0fc38e09414323922a3883a3c9f6306cf5f8e96f1722c4e93bb95942c410cecf0ce8b15b3328311a464b302595452fb66afb38391bdfe4f8cba05cb5e62b1172b15daba166b514eb095252951bc82ad71a9b99404d970c96c15e14db76ced99547659c9b89066e2ed3d93508a960be9fb1ea81df3a8751a80526a9d69a30166ac745a50196aad13049cb68ed3da19dcba8093ab9c2abe7581ff4ee89807a25d5eb9755655c7e9fd006f5c41937796add83a0876e5c53b923580bddc69a30c658c23ae354004dc7bf721024cf8593332a4d17b733a2bcd793fc016b3ca982105e5cc6c8af19cebd54618822c6388ada0483a34988b7512cc25a9b6966e54f840856c8d7c890156e0182bab30a115efac55d6fad9f9c057e26cf85b04fedfd569e53fe90d6dbdb5801549db5552ce03e587b46adec6865e180fed7a907289434c398d341178a3a60dae71d70427021ab9368a7621e9d33b3b6ee39d629e7289302daad0a2e8f54029737a2c23ab57761681019d006ea0ddc6f0a89022119771eedb4c47f7091d3271b2319163c89828a9e33c8c9cf7d1e04f44d36c21048b0961fc105d33004ccd98f338648c000946819c02c9900018891211141e81c6600cf280000)

**Comment by diegomura** [comment]
It's not supported actually 😄 
Thanks for reporting it. Keeping this open for future implementation

**Comment by diegomura** [comment]
Using `flex` instead of `flexGrow` solves this issue. Please refer to #523

**Comment by tommmyy** [comment]
@diegomura but word-break is still not implemented. Can I help somehow?

**Comment by hardiked** [comment]
I have the same problem. It is working fine when I am typing words with spaces but when it has no spaces, it overflows from it's container and overlap other text. I am using flex with four Text inside View. Looking for help so that it can break on the new line like word-break property in css.
<img width="598" alt="Screen Shot 2019-05-29 at 1 47 47 PM" src="https://user-images.githubusercontent.com/22965398/58541359-f7d0e800-8218-11e9-923d-4da0a5f5d40f.png">

**Comment by diegomura** [comment]
As a temporary solution you can insert SOFT-HYPHEN chars In the valid breaking points (after each / in your case, for example)

https://www.fileformat.info/info/unicode/char/00ad/index.htm

**Comment by tommmyy** [comment]
I hope following snippet will help you:

```js
import { isString } from 'ramda-extension';
import { curry, compose, o, join, map, split, splitEvery } from 'ramda';

const makeBreaks = curry((breakChar, maxLength, input) =>
	compose(
		join(''),
		map(o(join(breakChar), splitEvery(maxLength))),
		split(/(\s+)/g)
	)(input)
);

const Text = ({ hardBreakAfter, breakChar, children, ...rest }) => (
	<BaseText {...rest}>
		{isString(children) ? makeBreaks(breakChar, hardBreakAfter, children) : children}
	</BaseText>
);

Text.propTypes = {
	breakChar: PropTypes.string,
	children: PropTypes.node,
	hardBreakAfter: PropTypes.number,
};

Text.defaultProps = {
	fontFamily: 'body',
	hardBreakAfter: 10,
	breakChar: '\u00ad',
};
```

**Comment by rblakejohnson** [comment]
I've run into a similar issue and using `flex` instead of `flexGrow` doesn't fix it. I have urls in a that are breaking to 2 lines and there's a hyphen inserted. This is not appropriate in this case because the added hyphen makes the url incorrect. So if there's text in the pdf that says "Visit subdomain.myexampledomain.com" and it breaks to 2 lines and adds a hyphen "Visit subdomain.myexampledo-main.com" now the url is incorrect. 
I learned about `Font.registerHyphenationCallback(word => [word])` to turn off hyphenation, but now the url is wider than its container and "word-break: break-all" isn't supported so I can't break the url without hyphenation.
Here's a version of @antonin-arquey [REPL](https://react-pdf.org/repl?code=3d30041540ec18c1ec16de0534805d4a80593401b025a4380464aeb00ee1ac180ae013a4a2c0198ba26027800eda4021aa7cb12002810a001888d400e9e9200e6f8033aa24f40048f3e8386400c2fd72e62fda006b00141563d0026a002f003e5001b56c380ba012803728a89c241aa81aa72e120ab3a80032aa24521c76121cb402a092158037a8a8063e2a144017281e41417c3f3d32a41940130003000d3e654b0c9c7e00179223402b1b6546120007aa00208122bd680039340a3abd3cf0e559a5a2bd2c2d243d81ac393d197cc03112000b15d5dafb417a84c008921c3d1e88a9defd8681111dc8d1ea8000abbd429d7a3c0bedc6e069a0fc1512001a0002fbad88b07b270ca150e944c600711d850ca0046759a3dac49c7dd402c7c5132864f5815e9e327be014d02127c16c4e46520ac472258692336613a9a0727b505a30998af1e3328019859a02f3d80042990b29d88ba802d31970c8aa8d4ea64d6acbd62c7c099498ad6432a50d7566c2cdb5dbed0ec75385d49974b83400ec02db7db700d275d25d4cd01bb691eaf77d7d767f520006c9990c35ece1f69da4c2a98c4b192484fbbcc9e9daa68ee98585c43000e4ccaa1a05d66472ea5b8c57132364ed67df593a36900d002712055618a5b4510120b0444617b2c1a0b12b3b4003c4f0ded19068172d27700057e228702a5e9209c002249a5defcc7a3e1961f4803f70fc7d8a9e1b0bde2788c050ee000ca10162d22304451138392c1d12c842314480a2d06542a3d0d003e982a0a83702a09420121143e0163e0b0bd8f83f0b21d88a30064451c018176120f0000fa944a887bde1870120414ac428f02800024a11878613b8b190409230ee001abbe54221f06212a2c81896228bc9205292a784891c10871948712ba4610a702e33a06a69949269408a2a00fcc42d08a09ee42408a0f1c43aed5210f212026a709909861485117798a005fc21002320b21c0f03002a0206926084031d802856654324d9131e9824ee455d9667a966539b665982609c27b1a037187ab9a3b8445280fc320a80b4a008488b72690305d751dc2a8f8340d9680641142d222f63ae483e0b40a8f0262ea3c0dc1d88414dd47d87b2a0b4314fc0620a1a4ebb1cec65e02318f80008eb43f0e03a0283e0f03e5233f08e3c0843bda00006e6f7757d63daa280902c06a3d0b4238e31c24527ea02d026375701e0a74ed3124013723a827d951dd60f703358c337f0fd420eb7ae94e844823d822c8a013cb4383fc31d382720c0e0975d8cd588f54810a3700a1f03f1bee821080d1cb4370a816480ecdaf4a888bf591a1eb2013856d925415c032948050bae8106ea995439512691671b0569b4652455639b2116518b9c00dba0795f6c991a721b547b95235a24b5a26f3f4075e8375691f5036bcea11de1f7d9444d534f933410bd78448238eb8130532dab753a316d7ceedf83ed875e318d9d381a46d55da0354b305344d3d4ccbd334e31f60b5f4fd7f68940ce320e8060f6350ea030dc363023f2cf24c0a33fbc0e8cfe6778338cde78de75d410c4e93e4e5388262342c70cdc8cceb3313b3ea33530c28f5e9702cf70530ba2ca0e2e7552c0332dcb0ad0319ccd2ac7014d1301acb5b0072a36c64a9b48176decafb6b65acbd9c0eaa7ec261d527ea0083b35492a1dda8de48e3d463aae38ec351398d14ed34959f505a6d4b781735a9898bb6d70e65c2b9a02ae2bcd88cd74061c70137010dbc1e9b7080af4bb96f6fa8ddfba2b21ef014185f086e3d27a9319e48c179a31a09c2df3635c6c75c44ef56624dc63ef14ad4d8fb10d3e4cc599b30e637db9bdf1618fc9f8bf24062c3407f2605fd702cb59e380ffa75688aad80578f809ac9fb6b62a5ad6079b5f62ec551bb481fac548c0c32c829d820b095121d85b2422ed2e3c4c41b65bd9de6c9354d04072126c5838e0fb111cbaa10da6835e388d24ee346f2a7450e9ce69671ceb00e84ad0618e136b30fe67b5cba5763ad5cb85d75e18dc6e8b77d1b444467777ae22fb9776913456448f79190da1ac3651d85119cf646a8c97868cc65a2218e8fc6183046ef2312140fa98869f4c9e99f2b197c6c5733be61df996f671ae225bf36965e27fb5f3f1cad027ab109602207e5281493a4a24c367a46485e2bc02464bee6808799609e25ca2000128856e46789e24860afb03415875cd00971000) example with my non hyphenate url use case.

**Comment by idrisadetunmbi** [comment]
@rblakejohnson, please were you able to solve the above issue?

**Comment by rblakejohnson** [comment]
My workaround was to adjust column widths in my layout. 

Thanks,
Blake

**Comment by 1Jesper1** [comment]
I would also like this functionality :)

**Comment by ACPK** [comment]
@rblakejohnson Did you find a solution?

**Comment by SatorCube** [comment]
This would be a much appreciated feature.

**Comment by gwalshington** [comment]
This seems like an obvious ability. Would love word-break to be supported

**Comment by mcostajr** [comment]
function breakName(name: string): string[] {
    return [name];
  }
  
  <Text hyphenationCallback={e => breakName(e)}>Name With Spaces</Text>

**Comment by danny-does-stuff** [comment]
After reading the docs on hyphenation, I thought that setting the hyphenation callback was all or nothing. Thanks @mcostajr for pointing out that it is a prop for `Text` as well!

**Comment by er-santosh** [comment]
> export const chunkSubstr = (str, size) => { const numChunks = Math.ceil(str.length / size); const chunks = new Array(numChunks);
> 
> for (let i = 0, o = 0; i < numChunks; ++i, o += size) { chunks[i] = str.substr(o, size); }
> 
> return chunks; };
> 
> Font.registerHyphenationCallback((word) => { if (word.length > 12) { return chunkSubstr(word, 10); } else { return [word]; } });
> 
> worked for me

Is there any way to resolve with this logic and not appending hyphen at the end of the line.?

**Comment by RichMatthews** [comment]
Why is this closed?

**Comment by TransonQ** [comment]
```js
<Text>
  {description.split("").map((s, idx) => {
      return <Text key={idx}>{s}</Text>
    })}
 </Text>
```

**Comment by darrenzou2000** [comment]
> ```js
> <Text>
>   {description.split("").map((s, idx) => {
>       return <Text key={idx}>{s}</Text>
>     })}
>  </Text>
> ```

This is  such god awful code but quite literally the only thing that works 

I mean if twitter can wrap a single profile image in 67 divs  IDGAF
