### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by yuchi** [diegomura/react-pdf#261]
**Description:**

On NPM there’s already a well established [`react-pdf`](https://www.npmjs.com/package/react-pdf) package built by @wojtekmaj.

The fact that this project uses that exact name but in scope form makes a lot of confusion.

May I suggest both of projects to come to a “political” (also, ergonomical) fusion with…

- `react-pdf` that becomes `@react-pdf/viewer`
- `@react-pdf/react-pdf` becomes `@react-pdf/render` (or similar)

Also thanks to both of you, the libraries looks awesome!

**Comment by diegomura** [comment]
Hey @yuchi . Thanks for showing interest in the project.

I agree with you that this name collision can be confusing, and I appreciate your suggestion (I think it makes sense). However, I see some issues with it:

- `react-pdf` becoming `@react-pdf/viewer` I don't think it's viable, because that would involve @wojtekmaj transferring his project under an organization he does not own or know, and that's something I cannot expect him to do. He deserves owning his work in those terms, and I cannot ask for that (not that I would have a problem with it)
- In some circumstances one of the projects that collide is either unmaintained or just a silly project, but in this case both are serious repos, so it's not that someone can grant the name to the other. Specially considering that `react-pdf` was already there when I started this project.

About why I choose this name when one was already there: I never meant this project to be usable in any way, to be honest, so never put that much thought on the name.. I started it for giving a talk, and then I just went on building it. And since originally this was a monorepo, having the `@react-pdf` scope just made it possible. Also, I found out about `react-pdf` way before I started this (my bad 😞)

I take full responsibility of it, but in other way it's just how this ecosystem works. We constantly see issues about npm (in general) and in particular about name ownership.

Keeping this issue opened to keep the discussion open, also in case @wojtekmaj has something to say

**Comment by wojtekmaj** [comment]
Here's what I think:

Renaming `react-pdf` would cause a lot of trouble. There are people relying on patches I'm providing. So If I started publishing `react-pdf` under a new name, chances are a lot of people will be missing out, and trust me, there's a lot going on under the hood, both on mine and Mozilla's side.

npm will not allow to unpublish `react-pdf`. My project will live under this name forever, *whether I like it or not*. What it means that if you continue to publish `@react-pdf/react-pdf` the confusion will stay with you even if we take some action and rename our libraries.

[Judging by the popularity](https://npm-stat.com/charts.html?package=react-pdf&package=%40react-pdf%2Freact-pdf&from=2017-03-03&to=2018-07-31), it would make far less confusion if you renamed it to `react-pdf-renderer` or something similar as suggested above.

On the side, I'm a little sad, because I wanted to start opencollective soon, which this name clash will make a lot harder.

**Comment by diegomura** [comment]
Thanks for reaching @wojtekmaj 

First, please do not think this was in any ways a petition for you to change your project's name (just in case). I do realize that can't be done, even if you wanted to.

This is starting to feel like a ghost hunting me from the past now 😅. As I said, I do recognize it was my mistake at the very beginning of the project. I explained the reasons, and I can assure it was not bad intended. Maybe I would just wanted this to appear sooner, and not now that I just renamed the package for the new version.

Using both a GitHub org and npm scope is not something I'm open to change. This project has grown a lot, and divided into several subprojects or forks. Renaming the scope to `react-pdf-renderer` it's not something I'm attracted to either (too long? idk), but I promise I'll give a second thought to it. Renaming the main package to `@react-pdf/react-pdf-renderer`  will not solve anything.

I also admit I'm a bit lost on this subject now. I am pretty alone in the project, and don't want to screw it.

About open-collective, I don't mind looking for the change to change my project to `react-pdf-renderer` there, and leave you the name if possible. If you ever do, I think we can solve that easily.

**Comment by diegomura** [comment]
Ok. So I changed the main package name from `@react-pdf/react-pdf` (which was a bad idea and confusing) to `@react-pdf/renderer`. I'm keeping the npm and github org as it is because is important on how I like to organize things. This repo name will also keep the name for the moment. I hope this ease the confusion in the future, at least a bit. And I'm considering this as closed 😄
