### ISSUE TITLE
Infinite loop hanging megathread (minPresenceAhead, margin, break)

### ISSUE THREAD

**Issue by tom2strobl** [diegomura/react-pdf#2659]
# Description

1) There has to be a general flaw in the layout logic resulting in infinite loops that crash browser engines _(and whatever the issue might be it is evident that crashes are the worst expression of failure handling)_
2) (maybe related or not) minPresenceAhead works on the simplest examples but fails to work for me in any real-life scenarios where nested Views (eg inevitable for rendering bullet lists) and page padding (necessary for my case) are used

Note that I use 3.3.8 which afaik should already include https://github.com/diegomura/react-pdf/pull/2400

## Preliminary work

Regarding 1)

- https://github.com/diegomura/react-pdf/issues/1384 is related, simply nothing really happened since 2021
- https://github.com/diegomura/react-pdf/issues/2083 was closed (because OP gone rogue) but seems to be related
- https://github.com/diegomura/react-pdf/issues/2303 was closed but seems to be related
- https://github.com/diegomura/react-pdf/issues/2242 might be related
- https://github.com/diegomura/react-pdf/issues/874 might have been related

Regarding 2)

- https://github.com/diegomura/react-pdf/issues/2595 absolutely is related and showcases it pretty well
- https://github.com/diegomura/react-pdf/issues/955 seems it doesn't work for a lot of folks for a very long time

## Reproducable cases
_(note I'm using @jeetiss REPL for hanging issues since you obviously can't share an url of the official REPL if the process hangs)_

1A) [Simplest reproducible case REPL](https://react-pdf-repl.vercel.app/?modules=true&cp_code=JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAKtgB6FwAKAhgObZwC-cAZlBCHAOQACU2GmhgBaMABNWAegG5x2AVG4AoZeUiw481jQwAbeAAoAlHAC8APjiHlcOAB5UmHPgu27D2gzgBnYAC9sMwQAbQAmAAYIokiIgF0mNw8Pe1IKC3spNJgrdztMr2wkhyknLDwc5WNlIA&version=3.0.2&gz_code=eJxFzLEKgzAQxvE9T_FtKrTErkVDkQ4dO_QFgjklYIykJ1gk795YkS7H_eHuZ93kA2PF3bezo5FPeNGS5lP3hIgueIfsFki3fJ5MJwONhgKFTAhafr-GOj0PjLxArZALoDowlSLlZu1rio3Hmz8D1euKSRtjx77xzN5dcSnLEjGqh63kdqiwC_IgKvm3C_EF1AA6Sg): (yes, this is still a thing, nobody confirmed it's fix really)
```
ReactPDF.render(<Document><Page><Text style={{ paddingBottom: 1000 }}>Text</Text></Page></Document>);
```

1B) [Reducing available space to make it not fit REPL](https://react-pdf-repl.vercel.app/?modules=true&cp_code=JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAKtgB6FwAKAhgObZwC-cAZlBCHAOQACU2GmhgBaMABNWAegG5x2AVG4AoZeUiw481jQwAbeAAoAlHAC8APjiHlcOAB5UmHPgu27D2gzgBnYAC9sMwQAbQAmAAYIokiIgF0mNw8Pe1IKC3spNJgrdztMr2wkhyknLDwc5WNlIA&version=3.0.2&gz_code=eJxNkUFPAjEQhe_7K94NSJDFxJMBYqJHDx7Ui_FQ2mEzsdsu7RRRsv_dWZDApelM8773ZsptF5PggKdoS0tBpnilvZ7vTN9TvJiG0GOTYovRQyJj5aZzmzpRcJQojaqK9keCo40pXjCeYLnCuAIWZ-RKCy2PrMy_tDx83M7nU-jx2SPLj9fWAZ1xjkNzj7s5-l6B69KcpCoe4mCtAb7Orf_mpdTGEH31HBO14C6XFi76mNRUYFrSqWwMmayQlATjuONs1RLkWR8zORWAuOQ2OggNuwEHy45dCYIi8GateJCc0ITWNMHAeN4WM8NjDDvjPWdVe18y2ClAKDkNsxtslKAy1fNgFsjO8OYlsaWMbBoWUXFMlmGQLXlKnLeF0JWkuKyZKIEaktmiPo6Lyz7q64VcV4t6WP5wX9SXX5lUf3j1pSE)

1C) [It's not padding-bound either, as decreasing padding, but increasing font-size has the same effect REPL](https://react-pdf-repl.vercel.app/?modules=true&cp_code=JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAKtgB6FwAKAhgObZwC-cAZlBCHAOQACU2GmhgBaMABNWAegG5x2AVG4AoZeUiw481jQwAbeAAoAlHAC8APjiHlcOAB5UmHPgu27D2gzgBnYAC9sMwQAbQAmAAYIokiIgF0mNw8Pe1IKC3spNJgrdztMr2wkhyknLDwc5WNlIA&version=3.0.2&gz_code=eJxlkc1qQjEQhfc-xdlVwXot3YlKoV12UejPpnQRk_EykJtck4m1Fd-9E0UUuhlyJpxvTibc9TEJ9niKtnQUZIw32mn9YPoe48W0hAPWKXa4eUhkrNz2bt0kCo4SpZvBgHZHgqO1KV4wHGGxxHAAzM_IpQqVR1bmX1rsP--m0zG0fB2Q5cdra4_eOMehnWkfh4MCV6U9WdVc45zFP6mNGvqCWscgrzpphvvKWj7HRB24z6WDiz4mzSEwHelDbQyZrJCUBOO452w1BcizXmZyagBxyV10EKrrAgfLjl0JgiLwZqV4kJzQhM60wcB43hQzwWMMW-M9Z3V7XzLYKUAoOQ2zrWOUoDb1cx0WyE7w7iWxpYxsWhZRc0yWYZAteUqcN4XQl6S4rJkogVqSybype1jisqjmelPXat7U_6jneXP5qNHgDxbqq8Y)

1D) In my production app I also have a case (it's a larger document and more complex case that I can't 1:1 easily copy over to a REPL) where marking one of the `<View>`s with `break={true}` also suddenly introduces the infinite loop hanging. Changing any `wrap` or `minPresenceAhead` props don't affect the outcome, yet changing some margins does (although I was not able to find a real pattern yet unfortunately). So I think it's not the implementation of wrap/minPresenceAhead per se but likely a more general flaw in the layout (splitting?) logic. I'll try to spend some more time somehow getting this into a REPL. My gut says that some certain composition of Views with certain paddings/margins (and/or page padding) is getting too large for the Page and then in the splitting logic it somehow falls into the infinite loop hole.

2A) [A more contrived Real-life scenario REPL with the minPresenceAhead issue](https://react-pdf.org/repl?code=3187b0760ce02e00400e043039814c0ca5027806c5025015d70860178601bc02819e040137a04b3090064500cca00b860158003001a1a7518b24005441c3e009800b004e00748a0072080ec8201b06d1b5104d6789920016bc60046798357cedfdfb2c1af6ed8d5ff91f1ccac00422050502000b67cb67a00ccea82eefc7acadacafccefc1a5400be5454a090b09cd82000ee18382824e4d4c620104c504ce07c00e40800461020d80450286dfee172304a6a9a3afa8662b8dc7c42c3004e08909c204b51306d4ba10803001482f42848009443622681d2b27c22570c37e656360fc64f92216191f7fed7920e3cc60ef182743627258c8e00075263d0a0963f989c14b484bdac708452241fe54643bee10896311c8da3e2504b205404938d045296955c3b47ad87865d686578692608a791f8c49614059ac7c3e72972f942b40600300079413aa560001ada0551aa510528061b2c028003cbeaf8755a0c000f4e6983acc0500018820224c6c261da005955aece0837f2d06d5034130005e2868bc97dd6f00d385af3e2e9417ea8d3343db3006c22086c072cd7a940002463a2bb2a8f411dc1852968443012464b36814a4b7692c909d0401cfc9de12d82e118ccb658d0baed1fb48162137e30351e904b3b9fcee7b6310e5fc42dd4b05052328804d625a25b23b68753a5deecf6c87d7bc3c078329e5047fd30c2cd9e30fa4d6199a9f4e67b3b45cc16451b16c12ccb1402b465ab5ad712bc1b0d99b56ddb2ecfc1ed7f1814741cee682cd3421001cc009cb669c176236725d6815db575df52912c2585014d4d7dcad7f58f6755d6d83d300bd4bdb0ff50310cf87bcaf47d9f3156737d6d64dda34d361fccb0dc00d8d8b52caf72c06082101ad5861c605829b6d85b36c3b610bb142fb5c2c7300872c2cd743f0d08894124b12388b22600a3c9654550011c0850818abc01561a9689e2015b086442ed96c38160565e11810cf6c945b18414ad2c5152b335485344e5340f02ab4d2a084c2d662a35634f0e3cf6f550be36f41224e8d00b134abe23f14cda192332cc233d3e0a33624518421a46e1a50e5dfe5c390158e01c518b2baf4abd8b6938ee2eaa4c1aa9c9aa7c5ade5c4e13df2a9a4efd7a9cbf54528b60254ec2d4cad20ed26cda1fa83210839468fbc6decaf3b3acd2aec822e3271269448872c507a0d8261a013470bc301b1904773fc365a000124062d8286b5703940011260e8e019a5680cf2886181330b0c00c650088207684a140e500169a05c2a00a699b946159bda32966b6991d99a1a816988882306c0dddb083c58c74d8b3cb88bc36c92b6a1378a8d76a531403b35c923a93b64b3b6edcaf6eba0af528aad2901d25e9d8decfac6eedbeec2b96c542d51f8106ff517c5a91999b016ee7a208ce58aa15aab569aa78b35ea813b6c3b6d6d68b5d6daa3b3f2eb4ed43ff3ca2dd52c0ab61edb69edd37a3835ec1b86a7626f2325029c01940b2a25032060039b1e012c675e83a2c0772ce320003e2d5683a2a0020967ee0e2bc001e000d498140ca2bd687557052028001b5e5454bcf5faa550d77a1732345000174f26c24716000053a220140c060050001058fcdf77a54405540f881544402b0902cd4b0aa1e3ab7000d4b2903b7f5fe1d5ffb1f53efa954003072910af99a21eabc602cf00e0a8878502ee3dcfb8e459ee68f05402c1d84c862f65e5426019c494d2960050a085e4db8775d2dddb02f727ec206001f7e19d0e882015492007b0f51e894c0a4f69e73d685940111d537b635413f0b6038772390c10889549bd3826647e391e8761421dc3785800c1b406852f328f43185e466130125b6072c50c653904e1442785f77e107c2469011ea69c7ac8f6e5780f02f5b14a2aa0a8b8696411ad82463918c7c8db1262cd198e214fcac4e0f340a3ec530c6eb01dc58b4c61c33bb98df1d1370004a096204254f309d42147549409fc607ef781aa151a94ba6da205820380fa30c4a0149d7c704b483eed2152c0b545d27a78b171e58c678c9c114287800324e860c00372e4f59d826c5d0c39933944502fe9d235374bf698c284acf19141cd0002a594ddc482071586b30388f214744708aa6a802327ab76f1f40be7e0b682404a3941802c1730c0279e6872750f599927c764b21073c651cbb173cf25a4b100e21b914180b7da6b00c19961ca570ac9fdc7220f4095221a5c8e69512a676f0b93fce655cc013352965f749b411e4bcc44d0c6007c840e0b284c05f9adc33002920101814d29e152a87a429c630ae146e04548b0e6a2d052433177cbc5f93097d7271afce01c00e10ca478cf6b178c7f8100884fd285cf325a806000ca19e7296010519ad337a20540c99083107b9669706073615cb05546d39312282a88b2185462c419c5a2878e2f8dd639b89f0dc43df36e6321c5b0b760eb14b2c0894dcd1935f92c158980c06ec0889c3702b01e49a3e94a0c190700e0007d7e14c0ed548d5966999534b1dd7d67894f16b5ac76cf32540240766f59410102344a44fcc14200209c06009c088301f5006fee00184361c00d8fb15b9e36a8d4dc54eae60638a02665bdf7a902403802b0bbab73755c9550a06c0601f873056ebbbf749c7ee1e896002b006512900c7ee6d93752c280a063771e94001a601dec689fa60106040961b02c0083300003491009e4b1f85a3283cd0a000013d80040c0182a7c686ff4b0550b8730e8b01128168b7aa605dd9a1205034fdfba02954ab1fb930088aea96089886948e80405434fd5431afc1642975f2b9af3ba779a59d98c8ced046153a07b22a8de68ab5401ad873c84c6af2e92f4f20140f42c853ae002eadd560b383b3f21e01d4c4d6f9e33b4aa0fba42038b3cad4daf3443d02d50200000)
_I removed any fancy logic, but kept a lot of styling on purpose so there's something more elaborate to test again when we're confirming a fix._

<img width="400" alt="minpresence" src="https://github.com/diegomura/react-pdf/assets/557074/2ce3cb54-ae0c-4476-858d-e3d7085b1c7a">

## Thoughts

Interestingly in my hundreds (?) of manual tests I never saw this:
https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/steps/resolvePagination.js#L44

@carlobeltrame Does 
https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/node/shouldBreak.js#L29
work recursively in a sense that the size and margin/paddings of child Texts of Views of Views are taken into accout? Also – is page size and padding taken into account for the bounding box of the flow? I am asking because of this comment:
https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/node/shouldBreak.js#L38

What I mean is, if the page has paddingBottom (green) and minPresenceAhead is within the canvas but inside the padding then maybe the following siblings are not taken into account correctly(?):

<img width="534" alt="SCR-20240227-ndmk" src="https://github.com/diegomura/react-pdf/assets/557074/82d8c552-bf10-4ceb-80c0-a164bb1579ac">

I understand that this GH issue might actually be multiple issues at once, but I have the feeling that there must be some general connection.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: nodejs (electron main thread, but happens in chrome REPL as well)
- React-pdf version 3.3.8

**Comment by tom2strobl** [comment]
So regarding my main issue 1D) I've dug around for 6 hours without a definite conclusion.

Total weirdness ensures:
- I've patched `asyncCompose` to log the name of the async fn that will be executed to find out where it's stuck looping and it consistently prints `resolveAssets` as the last line, from which one would like to believe it's stuck there and never reaches `resolveSvg`(the next step in the chain)
- here's where it gets spicy: commenting out the `fontFamily` declaration on the (very often used) paragraph `<View>` makes the document render, even though it loads https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/steps/resolveAssets.js#L28 the same amount font files (2 font files) and without issues (the fontfiles are fine, the fontkit font loading is fine, the buffers are complete and everything, at the end of the day this works for all other 99% of documents so why would it suddenly not work)
- now if you thought I was onto something – hell no: keeping the `fontFamily` but instead commenting out a **marginBottom** (yes, a margin) of the bullet list wrapper `<View>` (oddly specific) makes the document render
- same goes for setting all `break` properties to false, renders flawlessly

It really looks like a certain vertical flow position of a certain View or certain Text results in the infinite loop and the margin and different font size or breaking just contribute to that awkward spot.

I'm inclined my logging strategy doesn't work as a marginBottom can't have an effect on `resolveAssets` and instead it breaks somewhere else but the logs don't reach stdout due to infinite loops preventing the next tick that would print the log. If anyone has an idea how I could go about finding where the infinite loop occurs I'd be grateful.

**Comment by jakeprem** [comment]
I'm seeing roughly the same issue as well. We're rendering a list of entry components (elements in a medical record). Certain combinations will cause ReactPDF to go into an infinite loop in the `resolvePagination` step. In a flame graph, `relayout` ends up being the function called over and over.

For one of our problem documents:
- Shuffling the the entries fixes the infinite loop
- Removing all bottom margins fixes it
- Removing the `if (shouldBreak) {}` block from `splitNodes` fixes it.
- When I log each of the `if` blocks in [`splitNodes`](https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/steps/resolvePagination.js), I see that the loop initially goes into the `shouldSplit` and `isOutside` blocks, but eventually gets caught in the `shouldBreak` block and then always goes back into that one.

Like @tom2strobl said above, it seems like the margins might be a red herring and the bug is actually caused by a node with specific attributes being split.

I'm continuing to investigate the page splitting logic to see where the loop might be happening. Apologies for the relative lack of details and clarity in my comment 😁

**Comment by jakeprem** [comment]
Did a bunch of digging and debugging into this.

I believe the root cause is [`shouldBreak.js`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js) is causing nodes to be broken that would fit in the page on their own, but not with their bottom margin included. When there are no sibling nodes present, then the lower value (sometimes `-Infinity`) will be used, preventing this node from breaking. Otherwise we use the result of [`getEndOfMinPresenceAhead`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js) which is `child.box.top + child.box.height + child.box.marginBottom + getMinPresenceAhead(child)` (minPresenceAhead = 0 in my case).

We have `paddingTop: 35` set on our pages which causes the first node after a relayout to have `child.box.top == 35` (represented as 99 in the example below)

## Example:
- Height: 1000
- `child.box.top`: 99
- `child.box.height`: 900
- `child.box.marginTop`: 0
- `child.box.marginBottom`: 10
- `futureElements`: Anything with at least one child where `box.top + box.height > 1009`

1. `shouldSplit == false` -> [`height < child.box.top + child.box.height`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js) -> `1000 < 99 + 900`
2. `endOfPresence == 1009` -> [code here](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js#L36)
3. `breakingImprovesPresence == true` -> [`child.box.top > child.box.marginTop`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js#L39) -> `99 > 0`
- [`!shouldSplit && endOfPresence > height && breakingImprovesPresence`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/node/shouldBreak.js#L44) -> `true && 1009 > 1000 && true`

These conditions cause `shouldBreak` to return `true`. But when this child breaks, `resolvePagination.js` [will push it and all following nodes to the next page](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/steps/resolvePagination.js#L85) (in the [`splitNodes` function](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/steps/resolvePagination.js#L48)), while resetting its top. On the next loop, the first node will have its top reset. In this iteration, nothing on this node has changed to it will again trigger `shouldBreak == true`, and again gets pushed to the next page. This causes there to always be a `nextPage` in the `paginate` function, so [`while nextPage !== null`](https://github.com/diegomura/react-pdf/blob/1f8952e6bc137e02eaf96486559571a8622943b6/packages/layout/src/steps/resolvePagination.js#L258) will keep looping infinitely, as it will never split the problem node, and thus progress through the document.

## Workaround 
Using `paddingBottom` instead of `marginBottom` seems to work ok, but has some tradeoffs, especially if you're using background colors.

## Suggested Fix
- Does `getEndOfMinPresenceAhead` in `shouldBreak.js` really need to include the bottom margin of the node if we're already at the end of the page anyway?
- Should `breakingImprovesPresence` have similar logic for the bottom margin as it does for the top margin, only returning true if the extra bottom space is truly needed?

**Comment by cooperbrown9** [comment]
> I'm seeing roughly the same issue as well. We're rendering a list of entry components (elements in a medical record). Certain combinations will cause ReactPDF to go into an infinite loop in the `resolvePagination` step. In a flame graph, `relayout` ends up being the function called over and over.
> 
> For one of our problem documents:
> 
> * Shuffling the the entries fixes the infinite loop
> * Removing all bottom margins fixes it
> * Removing the `if (shouldBreak) {}` block from `splitNodes` fixes it.
> * When I log each of the `if` blocks in [`splitNodes`](https://github.com/diegomura/react-pdf/blob/fab09cc9814326fdb44d2bcb7097ba9960d441d1/packages/layout/src/steps/resolvePagination.js), I see that the loop initially goes into the `shouldSplit` and `isOutside` blocks, but eventually gets caught in the `shouldBreak` block and then always goes back into that one.
> 
> Like [@tom2strobl](https://github.com/tom2strobl) said above, it seems like the margins might be a red herring and the bug is actually caused by a node with specific attributes being split.
> 
> I'm continuing to investigate the page splitting logic to see where the loop might be happening. Apologies for the relative lack of details and clarity in my comment 😁
> 
> * We're running in Node.js; I'm testing against a local Express server
> * I've linked my test setup to a local copy of the `react-pdf` library so testing against the latest commit in master

Removing marginBottom on my mapped fields worked!! thank you!
