### ISSUE TITLE
PDFDownloadLink not working using Next js

### ISSUE THREAD

**Issue by zhangqhzz** [diegomura/react-pdf#2754]
"@react-pdf/renderer": "^3.4.4"
 "next": "14.2.1",
{myDocument && <PDFDownloadLink document={myDocument} fileName={project.company.jgmc + project.year + ".pdf"}>
                    {({ blob, url, loading, error }) => {
                        console.log("loading=" + loading)
                        return error ? error.toString() :
                            loading ? 'Loading...' : <><FilePdfOutlined /><span className="ml-2">Pdf</span></>
                    }}
                </PDFDownloadLink>}

console：
loading=false
loading=true
web: The page keeps displaying "Loading..." 
Click No Response

**Comment by antal-bukos** [comment]
I ran into this same problem and what I found weird is that it works without `Text` elements, but when using text `loading` is never set to `false`. Based on discussions on a different issue, it happens when using custom fonts in the text, it's caused by a dependency of `react-pdf`, this helped me https://github.com/diegomura/react-pdf/issues/2675#issuecomment-2000121503.
