### ISSUE TITLE
Precisely dimensioned components (for print)

### ISSUE THREAD

**Issue by moritzmhmk** [diegomura/react-pdf#278]
I found that the default sizes are based on 72dpi (btw is there a way to change the dpi?) and I only used StyleSheet with react native projects before and know that dimensions are "unitless, and represent density-independent pixels".

Should I assume 72dpi and calculate my dimensions based on that or is there a better way for dimensioning components for printing?

I do plan to create a letter and need the address to fit the envelope window...

**Comment by diegomura** [comment]
Thanks for showing interest in the project @moritzmhmk 

For the moment I think you should assume 72dpi and calculate your dimensions. I don't have much printing concepts, but which better way of "dimensioning components for testing" can you think of? Having the ability to change document dpi for instance? would that be enough?

Never put that much thought about units per se to be honest, because all react-pdf does is passing down units to pdfkit. I guess its possible to translate units on the react-pdf side along the road

**Comment by moritzmhmk** [comment]
Thanks! The info on foliojs/pdfkit#268 did answer my question.

**Comment by pavle-lekic-htec** [comment]
It seems that you can set dpi for pdfkit, there is an option for it, https://stackoverflow.com/questions/41924233/pdfkit-generates-small-scaled-pdfs

**Comment by pavle-lekic-htec** [comment]
It would be really great if react-pdf could pass that option down to pdfkit, because I noticed a lot of issues that might be caused by small dpi.

**Comment by diegomura** [comment]
Cool! I’m going to test it today. Wasn’t aware of that option. Are you sure that link refers to the js pdfkit? There’s some ruby code there, and a pdfkit lib written in ruby

**Comment by pavle-lekic-htec** [comment]
You're right, they were referring to a python PDFKit library, apparently there is a library with the same name in python.

**Comment by diegomura** [comment]
@pavle-lekic-htec I added son DPI logic to `<Page />` and would like to know what you think, since you needed that feature.

It's important to mention that the PDF spec does not have DPI (only images embed into it). the most we can do is transforming page dimensions from the default DPI (72) to the given one

**For example:**
Page A4 size = 8.3 x 11.7 in
At 72 DPI = 595.28 x 841.89 (what's currently on the lib)
At 400 DPI = ~3307 x 4677

This way, I think the result can be achieved. If you had a fixed dimension on your page (let's say, a view 100x100), after increasing DPI, it will look smaller. You also have more control over where elements layout precisely inside the page

HoweverI'm not sure if this is the ideal solution, since we are exporting a different size document. Maybe the ideal would be converting the points passed on styles given the page DPI, but not sure how complex and error prompted that would be with the current implementation.

**Comment by moritzmhmk** [comment]
When the PDF spec only supports 72dpi I believe it is best to not support different "pseudo DPIs" but adding support for defining length in inch and mm would be a nice addition.

**Comment by diegomura** [comment]
I also think that would be very nice. But would that solve the original issue of not having enough placement precision when printing?

**Comment by moritzmhmk** [comment]
It would solve my problem. 😉 

I do currently use a function that takes mm and calculates dots assuming 72dpi - which works just fine.

**Comment by diegomura** [comment]
@moritzmhmk @pavle-lekic-htec react-pdf now supports `in`, `mm` and `cm` as valid units.
I'm going to add docs now. It's going to be available on next publish

**Comment by ribas14** [comment]
@diegomura I can't find the info of how to set the page in cm, can you help me? I need to create a pdf with exacly the same size of an image and with 300 dpi

```js
const styles = StyleSheet.create({
  image: {
    height: '100%',
    width: '100%',
    objectFit: 'cover'
  }
});

export const Pdf = (props) => (
  <Document>
    <Page dpi={300} size={{ width: props.width, height: props.height }} wrap={false}>
      <Image src={props.img} fixed={true} style={styles.image} />
    </Page>
  </Document>
);
```
