### ISSUE TITLE
Umlaut Support

### ISSUE THREAD

**Issue by moritzmhmk** [diegomura/react-pdf#280]
**OS:** mac OS 10.13.6

**React-pdf version:** 1.0.0-alpha.12

**Description:** Umlauts are not rendered.

**How to replicate issue including code snippet (if applies):**

``<Text>ÄäÖöÜü</Text>``

Using the HTML escaped umlauts (``&Auml;`` etc.) works but is not practicable for User generated texts.

**Comment by moritzmhmk** [comment]
Changing the font fixes this. The default font should support UTF8 -.-

**Comment by diegomura** [comment]
By `changing the font` you mean adding a custom `.ttf` font or what?

**Comment by moritzmhmk** [comment]
```js
Font.register(
  'http://localhost:8080/OpenSans-Regular.ttf',
  { family: 'OpenSans' }
)
```

btw. 

```js
Font.register(
  'OpenSans-Regular.ttf',
  { family: 'OpenSans' }
)
```

throws 

``Error: fontkit.openSync unavailable for browser build at Object.fontkit$1.openSync``

**Comment by diegomura** [comment]
The default font is a standard font, supported by PDF by default. It's Helvetica, but can be courier or times. But I cannot ship the lib with a default `.ttf` font file, because that would do the library even more heavy, and people would be forced to load a font they might not need or want. The way to go is: if the default works for you, you can use it 👍 , but if you need some extra chars that aren't there you need to provide your own font. I'll look further into the umlaut thing in these fonts, but I think that will remain the same.

About the snippet you shared, it's correct that throws an error. When using react-pdf on the browser you must specify a valid url from where to load the font. Just `OpenSans-Regular.ttf` it's not a URL. Maybe you can try a relative path like `/OpenSans-Regular.ttf`, but the other one it's just wrong. I understand that the error message can be more descriptive maybe, but it's mostly because on Node you can specify a path to a font in your file system

**Comment by moritzmhmk** [comment]
Using the builtin Helvetica (setting it via the StyleSheet) works as well. What Font is used when not setting a FontFamily? 

A relative path throws the same error. Maybe it should handle a path like an URL to the current host when used in the browser.

**Comment by diegomura** [comment]
Yep. I think that last idea is good. I'll try to implement it, but it's very minor.
By default is [Helvetica](https://github.com/diegomura/react-pdf/blob/master/src/elements/TextEngine.js#L86). Didn't have time today to actually test it, but I will and see why it's not working

**Comment by diegomura** [comment]
@moritzmhmk Ok. I did a quick test on the REPL (had too much curiosity 😅) and all chars got rendered correctly.

You can see it [here] (react-pdf.now.sh/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080be3003b80271e001dda74e5400a86146c008c013806b00de00ec01faa01e94f983475ef015eddd03332b3b010037191928242c3486040e0c00329428861240058606142cb016860f261e0487228a80170c2961ae8f129292181f31882e954033002b000d07251d43535f0010ba14082315401b2f7f4c20e37340048816920017b8140f08a75ce52a9f6ab8644012a17014170d0018ac81581286169e15222a3a162bb129d00)

Or the result here: 

<img width="672" alt="screen shot 2018-08-08 at 11 46 58 pm" src="https://user-images.githubusercontent.com/5600341/43875039-61d05c90-9b65-11e8-85f3-667ad1dfe4ab.png">

As you can see there, I'm not applying any styles to that `<Text />` element, and gets rendered in Helvetica.

What's exactly what you saw as an issue?

**Comment by moritzmhmk** [comment]
I saw white spaces but I cant reproduce it anymore either 🤷‍♂️

**Comment by moritzmhmk** [comment]
I did copy an umlaut from the original source and it seems that the character looks like a normal umlaut but isn't. The second ä [here](react-pdf.now.sh/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080be3003b80271e001dda74e5400a86146c008c0139e80218001ac037803b007ea807a53e60d18fbc057d3ce8199959d80801b8c8c9412161a4302070600194a1443152002c3030a16580b4307930f02439145400b8602b0d7478949490c0f98c41756a01980158006839291b9b5af80085d0a041196a00d8068660465ada002440b49000bdc0a078447b1729550754a26200944b80a0b86800c5658ac09430b4f0a91151d0b03d882e400000) gets rendered as a + whitespace.

Strange but doesn't happen with umlauts entered from the keyboard...
