### ISSUE TITLE
Not bundling cjs and es with rollup

### ISSUE THREAD

**Issue by klis87** [diegomura/react-pdf#290]
I wonder, if there is any particular reason rollup is used for cjs and es? I think this is better left for app consumers to do it and bundling should be here done only for UMD.

For instance those scripts could do it:
```json
"build:commonjs": "cross-env BABEL_ENV=commonjs babel src --out-dir lib",
"build:es": "cross-env BABEL_ENV=es babel src --out-dir es",
```
assuming example `.env`:
```js
{
  "env": {
    "commonjs": {
      "presets": ["env", "stage-3"]
    },
    "es": {
      "presets": [
        ["env", { "modules": false }],
        "stage-3"
      ]
    }
  }
}
```

With such setup, people using Webpack or Rollup in application could take advantage of treeshaking - if they don't use at all some of reexported modules from here, those wouldn't be included in their app bundle at all. Also, it would still work on server side - NodeJS handles cjs import natively.

**Comment by diegomura** [comment]
Hey @klis87 
I understand (and agree) with your points about treeshaking and not distribute the library bundled by rollup.

However, there are some reasons why this is done by that:

- Since react-pdf is now shipped in a single package, we need a way to ensure it runs in both environments without issues. Rollup "patches" or ignores some dependencies (in this case `fs` and `path`, but some others among the other dependencies react-pdf uses) to make this possible.
- Besides that, it also removes some chunks of code based on what type of build it's exporting

Libraries such as `styled-components` are doing something similar to supports multiple envs.

Even though treeshaking is always desirable, in this case there are not so many parts of code you can get rid of. The most important use case would be not using `<Text />`, which uses some specific dependencies, but it's the least of the cases

**Comment by klis87** [comment]
@diegomura Thanks for the answer, good job unifying monorepo into one repository, it is much easier to use know :+1:
