### ISSUE TITLE
`@react-pdf/renderer`: Support CommonJS Exports Again

### ISSUE THREAD

**Issue by CodeSmith32** [diegomura/react-pdf#2907]
Specific to package: `@react-pdf/renderer`

**Is your feature request related to a problem? Please describe.**
Our environment is poorly built. We will eventually restructure, but in the meantime, it emits CommonJS files. At the moment, because of the drop in support for CommonJS exports since v4.0.0, we are unable to use 4.0.0 and we had to downgrade to 3.4.5 due to a number of interop issues.

**Describe the solution you'd like**
Please provide the .cjs files in the /lib/ directory again.
Compared to version 3.4.5 which has all the files below, please re-add the files pointed out which were removed as of 4.0.0:

```
react-pdf.browser.cjs       <---
react-pdf.browser.cjs.map   <---
react-pdf.browser.d.cts
react-pdf.browser.d.ts
react-pdf.browser.js
react-pdf.browser.js.map
react-pdf.browser.min.cjs   <---
react-pdf.browser.min.d.cts
react-pdf.browser.min.d.ts
react-pdf.browser.min.js
react-pdf.cjs               <---
react-pdf.cjs.map           <---
react-pdf.d.cts
react-pdf.d.ts
react-pdf.js
react-pdf.js.map
react-pdf.min.cjs           <---
react-pdf.min.d.cts
react-pdf.min.d.ts
react-pdf.min.js
```

**Describe alternatives you've considered**
I had to downgrade to v3.4.5 until these are supported again.

**Additional context**
N/A

**Comment by lucswart** [comment]
Same issue here. Downgrading to 3.4.5 works, but it is a bit unfortunate.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by CodeSmith32** [comment]
All: ummm288's comment is spam / abuse, and the link contains malware. I am reporting him now.

**Comment by ashapir0** [comment]
It's disappointing to see the maintainers move in this direction. It's opinionated and does not account for organizations with other considerations when deploying applications. Switching a large codebase from CJS to ESM in an enterprise environment is impossible to do quickly.

We refactored to use this library some time ago and are now coupled to it. Finding a replacement because the maintainers decided it would be "simpler to drop support" is selfish. This library will not be the catalyst the maintainers think it will be to get folks to adopt ESM.

We are now in a state where we have to manually hack different versions of sub-packages to fix bugs using forced module resolution.

**Comment by ashapir0** [comment]
> I was under the impression this was accidental. @diegomura, was this an official decision?
> 
> (It cannot possibly be that hard to also generate cjs files, esp. seeing the facilities were already in place for so long.. why drop support?)

See here: https://github.com/diegomura/react-pdf/pull/2711#issuecomment-2366834537

**Comment by CodeSmith32** [comment]
Ok, so the real issue is that the `yoga-layout` package has refused to provide cjs support, which has screwed things up down the line.

Fortunately, I'll be dropping use of `react-pdf` in the semi-near future anyway (for unrelated reasons). Sad to see others will probably be forced to due to lack of cjs support..

**Comment by diegomura** [comment]
This wasn't accidental. I'm sorry to hear you are having issues due to that decision, but as explained in the linked thread it was needed on our side because of yoga-layout. We won't be bringing cjs exports back. Besides yoga which was the main reason why we did it, it allowed for a lot of internal simplifications which are always welcomed.

**Comment by robert-pitt-foodhub** [comment]
Could you consider continuing making fixes for the version 3 line, for example v4 supports react 19, but version 3 fails

```
[/aws/lambda/falcon-rp-pos-hub-billingautomationprocessinvoiceq-fx8BgpXbSJWa] 10:30:58 PM 2025-05-02T21:30:58.427Z      e53d28d6-ed6e-5bf3-9e46-4859d6d1ea1f    ERROR   TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at $$$reconciler (/opt/nodejs/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:99:6)
    at createRenderer (/opt/nodejs/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:3998:10)
    at pdf (/opt/nodejs/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:4211:26)
    at renderToStream (/opt/nodejs/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:4351:20)
    at Object.renderToBuffer (/opt/nodejs/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:4378:35)
    at PDFService.renderToBuffer (/var/task/index.js:1561:35)
    at BillingService.sendAccountInvoiceEmails (/var/task/index.js:2861:44)
    at BillingService.runAccountBillingProcess (/var/task/index.js:2735:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.allSettled (index 0)
```
