### ISSUE TITLE
Package name is already taken

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#30]
Unfortunately `react-pdf` is already taken on npm (https://github.com/nnarhinen/react-pdf) so we will have to come up with another name 😓 .

@jbovenschen what do you think?

**Comment by jbovenschen** [comment]
We should come up with a different name, don't know any good ones atm.
Another solution would be to create scoped packages like `@react-pdf/core` and `react-pdf/dom`.

**Comment by diegomura** [comment]
I like that. I mean, I dont want to come up with a different name than this one, it's pretty straightforward. On the other hand, I don't want to create confusion between other dependencies. I'll read about that and if the solution fits maybe I'll publish some dummy version just to save the names

**Comment by rofrischmann** [comment]
Maybe just try to contact the owner and politely ask for the package name :P 
I think it would be much better to call it react-pdf-viewer or sth. as it is a component just to view/display pdfs.

Another idea would be to call it sth. like react-pdf-renderer? or react-to-pdf.

(I once started an experiment as well using React to generate PDFs and came up with the name react-to-pdf, but your package is much more stable and mature than my experiments have been, so I won't publish anything^^)

**Comment by jbovenschen** [comment]
The react-pdf package is something which is download pretty often so it would be really weird for their end users if the package would change to something totally different. 

Because we have a mono-repo the org feature within npm is pretty suitable, also if we have the @react-pdf org on npm we have all the freedom to add new packages within the feature, and don't need to worry anymore about if a package name is already taken. 

The packages you would install will be:
```
yarn add @react-pdf/core
yarn add @react-pdf/node
yarn add @react-pdf/dom
yarn add @react-pdf/native
```

And in the future we could add custom plugins to it like Video support...

Cool that we were not the only one having this idea, if you have interest in this project do you like to collaborate on it? We need to do a lot of stuff until it will be fully stable and usable.

**Comment by diegomura** [comment]
I think that's the way to go. I dont see another coherent alternative

**Comment by diegomura** [comment]
Closing this. We already have those names
