### ISSUE TITLE
Page number reset feature

### ISSUE THREAD

**Issue by lDevas** [diegomura/react-pdf#315]
**OS:** All

**React-pdf version:** 1.0.0-alpha.17

**Description:** 
Hi,
I've been trying to generate a PDF where it's paging resets mid-document several times (As if it were multiple documents bundled together) and it seems like currently, there's no way of doing this.

Also, according to: https://react-pdf.org/advanced#dynamic-content
render should be called twice, which is not what I am currently seeing (bug or outdated doc?).
I mention this, because with that, it would be possible to implement something like that.

I guess something like this could be helpful to be able to reference pages that come after what's being rendered currently (Like "This will be reviewed later, in chapter 6, page 120").

**Comment by diegomura** [comment]
Hey @lDevas 

This seems to be a very specific feature. What API do you propose to achieve something like this? Resetting page counter for each `<Page />` would be enough? This is the only thing I see _possible_ to add in the future.

About the render callback, [checking the code](https://github.com/diegomura/react-pdf/blob/master/src/elements/Page.js#L124) I saw that it gets called twice only if the element is `fixed`. If it's not, the render property gets removed after the first call. This is because currently `totalPages` (which is something unknown until the very end of the rendering process due to possible dynamic content) is thought to be used on fixed page counter texts.

Not sure how much time I'll have to work on this soon, but PRs are always welcomed 😄

**Comment by lDevas** [comment]
Yes, it's definitely something specific, and definetly not trivial, I have yet to find a library that allows something like this.
Regardless, I did find a way to do this. with some fixed components, one to "reset" an internal counter, which doesn't really render anything, and another one to actually render the page number.
I was using fixed components, however, it looks like they need to be in the "root" of the Page component for them to be called twice, is this expected?, I see how this could be intended, but It would be nice to document 🤓
The approach that could be better (and would apply to other cases) is to allow pdf merging, that's definitely more general, and would solve this. However it seems a way more difficult issue.
So... I guess we can either close this, or leave it open as a feature that would be nice to have?

**Comment by lDevas** [comment]
Yes, I am aware this is a hack, I'll probably lock the version so it doesn't break on an update or install.

As for your question, I guess it would make more sense on a page level, instead of at a Text level, where some strange behavior can happen, like, what if the text is broken into multiple pages?

I've never actually checked out the code, and PDF generation is quite new to me, so a PR with this feature including tests might be a bit far off, but I'll take a shot!.

Yeah, I expected that merging documents would be nearly impossible haha

**Comment by diegomura** [comment]
Should be covered in #1019

**Comment by Beej126** [comment]
bare min working online sample in case helps anybody: https://stackblitz.com/edit/react-pdf-demo2?file=src%2Findex.js
