### ISSUE TITLE
Element type is invalid -- problem when trying to render BlobProvider

### ISSUE THREAD

**Issue by jamestthompson3** [diegomura/react-pdf#329]
**OS: Windows 10**

**React-pdf version: 1.0.0-alpha.18**

**Description: When trying to render a `BlobProvider` Element, I get the `Element type is invalid` error

**How to replicate issue including code snippet (if applies):
```js
import { Page, Text, View, Document, BlobProvider } from '@react-pdf/renderer'

const PDF = () => (
  <Document>
    <Page>
      <View>
        <Text>Privacy Policy</Text>
      </View>
    </Page>
  </Document>
)

class Privacy extends Component {
  render() {
    return (
      <Wrapper>
        <BlobProvider document={PDF}>
          {({ url }) => (
            <a href={url}>
              <Button primary active size="2x" wide round color="secondaryColor" icon="document">
                Print PDF
              </Button>
            </a>
          )}
        </BlobProvider>
      </Wrapper>
    )
  }
}
```

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
Are you using react-pdf for the browser or node?
If you do, what tool are you using to build the project?

**Comment by jamestthompson3** [comment]
I'm using it in the browser, I'm using webpack to build the project.

**Comment by diegomura** [comment]
Oh I see what's going on. You're not passing the `document` prop as it should, since you're passing the PDF component definition. The `document` prop should receive the Document definition straight away. 

So or you either do `document={PDF()}` or you define your document as a plain variable

```jsx
const PDF = (
  <Document>
    <Page>
      <View>
        <Text>Privacy Policy</Text>
      </View>
    </Page>
  </Document>
)
```

Not sure what would happen if you do it like `document={<PDF />}`, since it's not supported yet. would be cool to do it maybe, but I'll have to study if it doesn't have ay downsides

**Comment by jamestthompson3** [comment]
That solved the issue. Thanks!!
