### ISSUE TITLE
flexDirection: row causes text to have no height

### ISSUE THREAD

**Issue by dberringer** [diegomura/react-pdf#348]
**OS:**
MacOS 10.13.6

**React-pdf version:**
1.0.0-alpha.18

**Description:**
For some reason Text elements don't have a height when being displayed as flex items where the container is defined with flexDirection: row.  flexDirection: column displays fine but row treats the text items like they have no height.  I would expect that it would work just like html.  
```
<div style="display: flex; flex-direction: row;">
  <div>Test1</div>
  <div>Test2</div>
  <div>Test3</div>
</div>
```

**How to replicate issue including code snippet (if applies):**
```
const doc = (
  <Document>
    <Page wrap>
      <Text debug>This text displays correctly</Text>
      
      <Text>----------------------</Text>
      {/* This text will not display unless at least one of the children is given a height */}
      <View style={{flexDirection: 'row'}} debug>
          <Text>This text doesn't display</Text>
          <Text>This text doesn't display either</Text>
          <Text>This text doesn't display as well</Text>
      </View>
      
      <Text>----------------------</Text>
      {/* This text will display.  At least one of the children is given a height */}
      <View style={{flexDirection: 'row'}} debug>
          <Text style={{height: '100%'}}>This text displays</Text>
          <Text>This text displays too</Text>
          <Text>This text displays as well</Text>
      </View>
      
      <Text>----------------------</Text>
      {/* This text will not display. Display block doen't seem to help */}
      <View style={{flexDirection: 'row'}} debug>
          <Text style={{display: 'block'}}>This text doesn't display</Text>
          <Text>This text doesn't display either</Text>
          <Text>This text doesn't display as well</Text>
      </View>
      
      <Text>----------------------</Text>
      {/* This text will display */}
      <View style={{flexDirection: 'column'}} debug>
          <Text>This text displays</Text>
          <Text>This text displays too</Text>
          <Text>This text displays as well</Text>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(doc);
```

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
Also thanks for this. I do remember seeing this issue in the past and being unable to fix it. But I'll try again. The issue is in Yoga, which tries to resolve the text layout before his `flexDirection: row` container. Because knowing the exact parent's exact width is necessary to layout text, it "crashes". However, I'll take a look and check if I miss something

**Comment by dberringer** [comment]
Seems like it wasn't an issue in a previous version but I wasn't able to find the previous working version so maybe I'm not correct.  Would it make sense to apply height: 100% to all Text components by default?

**Comment by diegomura** [comment]
Applying `height: 100%` to all components would create other side effects.

I debugged this case and was able to fix it _up to certain level_. The issue is that yoga returns the max width that each text can occupy, but the same for all siblings. So this happens:

<img width="655" alt="screen shot 2018-10-29 at 2 30 02 am" src="https://user-images.githubusercontent.com/5600341/47630976-93369900-db22-11e8-9784-18e8787159a1.png">

All texts in the row can scale up to the whole page widths, so they layout based on that. Unfortunately, when the last text of the row layout, I do not know how much space their siblings used, causing some texts to get out of the page.

I would recommend to use the `flex` (of `flexGrow`) attribute to hint yoga about how much width that column can have:

<img width="662" alt="screen shot 2018-10-29 at 2 43 55 am" src="https://user-images.githubusercontent.com/5600341/47631354-82872280-db24-11e8-806c-1993b34d42d6.png">

I know this is not taking full advantage of the flexbox API (setting columns using percentages would produce the same output), but unfortunately I could never find a way of replicating exactly what happens in the web on these type of scenarios.

This small change is going to be present on next version
