### ISSUE TITLE
Conditionally display elements based on value...not working

### ISSUE THREAD

**Issue by serkyen** [diegomura/react-pdf#359]
**OS:**
macOS 10.14

**React-pdf version:**
1.0.0-alpha.19

**Description:**
I am unable to show or hide elements based on values passed through with `fields`.

```
generateOrderPDF = (fields) => {

    console.log(fields.receivingMethod)

    return (
        <Document title="Order">
          <Page wrap size="A4" style={styles.page}>

              {fields.receivingMethod === 'Pick Up' ?

                  <View style={[styles.row, {}]}>
                    <View style={[styles.fieldName, {}]}>
                      <Text style={[styles.text, {}]}>Vehicle Type</Text>
                    </View>
                    <View style={styles.fieldValue}>
                      <Text style={[styles.text, {}]}>Value</Text>
                    </View>
                  </View>

              : null}

              {fields.receivingMethod == 'Delivery' ?
                
                  <View style={[styles.row, {}]}>
                    <View style={[styles.fieldName, {}]}>
                      <Text style={[styles.text, {}]}>Something else</Text>
                    </View>
                    <View style={styles.fieldValue}>
                      <Text style={[styles.text, {}]}>Value</Text>
                    </View>
                  </View>

              : null}

          </Page>

        </Document>
    )

}
```

```
<BlobProvider document={this.generateOrderPDF(this.props.form.getFieldsValue())}>
     {({ url }) => (
          <Button href={url} target="_blank" type="primary">Print</Button>
     )}
</BlobProvider>
```

When I change the value on the form, I see the console output the correct value for `fields.receivingMethod`, but whatever block was loaded the initial time the page loaded is the one that sticks. I have other fields and images in the PDF that do change based on the value passed through from `fields`. How can I conditionally display View components based on a the value that is passed through `fields`?

Also, to expand on this question, (I am guessing that I will have the same issue when I get there)...what would be the correct way to loop over an array and display a View/Text element for each array item?

**Comment by serkyen** [comment]
To expand on this question, (I am guessing that I will have the same issue when I get there)...what would be the correct way to loop over an array and display a View/Text element for each array item?

**Comment by serkyen** [comment]
@diegomura ...I am patiently waiting :)

**Comment by serkyen** [comment]
Ok, I fixed this problem by forcing the BlobProvider to reload each time a change is made on the form. Not ideal but works.

```
onValuesChange(props, values){
     Session.set('pdfPrintable', false);
     setTimeout(function (){
         Session.set('pdfPrintable', true);
     },500);
}
```

```
{this.props.pdfPrintable ?
    <BlobProvider document={this.generateOrderPDF(this.props.form.getFieldsValue())}>
        {({ url }) => (
            <Button href={url} target="_blank" type="primary" style={{marginRight:'5px'}} className="download-pdf-btn ant-btn btn-secondary ant-btn-primary" loading={false}>Print</Button>
        )}
    </BlobProvider>
:
    <Button href="#" target="_blank" type="primary" style={{marginRight:'5px'}} className="download-pdf-btn ant-btn btn-secondary ant-btn-primary" loading={true}>Print</Button>
}
```

**Comment by diegomura** [comment]
Hey.

Not sure what is going on, but the document _does_ refresh when data change. It seems to me that the form library you're using is not behaving well with react-pdf, but this is not a react-pdf issue. I would recommend you to do a quick test using just react state to check first if the issue is in the lib. 

My best guess would be that the `this.props.form` instance does not change (the data does, but you get the data by calling `getFieldsValue` always from the same instance), and that makes the PDF not to render again. IMO that lib does not follow the best React patterns by doing that, but I never used it so I cannot say for sure.

Maybe it has to do with that `pdfPrintable` prop. You know that you get a `loading` variable from the blob provider? Maybe that would be helpful

I would also recommend you to make your document a separate component, and not a response of a function call. Maybe that will solve your issue:

```jsx
const OrderPDF = (props) => (
  <Document title="Order">
    // ....
  </Document>
);

<BlobProvider document={<OrderPDF {...this.props.form.getFieldsValue()} />}>
  {({ url }) => (
    <Button href={url} target="_blank" type="primary" loading={false}>Print</Button>
  )}
</BlobProvider>
```

Anyway, that's all I can do from my side. Please check those points and let me know, but the re-rendering seems to me working fine for me
