### ISSUE TITLE
Disabling hyphenation with React-pdf 1.0.0 does not work

### ISSUE THREAD

**Issue by redcranesolutions** [diegomura/react-pdf#417]
React-pdf version: 1.0.0

Description:
Using doc example of disable hyphenation fails with React-pdf 1.0.0.

Code used:
Font.registerHyphenationCallback(words => (
  words.map(word => [word])
));

Replication:
https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c271802800607a5c02403780ee4980098825400d880318086112e1400588680beb9a2c9035c00cdc0414b80359c24632140810476003400088802875ea45300b6496804f005cea011006959f2225ad3c025006e2d1f402f8c8d06001226000e1c706082e000c24cb4b400464c0c52982420301428ea00bc007cea983aeaa9e92850064c41296914d97900dac51400bace5ace6e1e0ce068ea6826b4709959ea00ca10fd7023a170d00cf02c7098dabae8001e1016cbba7ae22348005e7016004c00acaa85baf6c086c6e656b672e28eba3c4e1d5a5d603d00824141d97cb396af9428007800228c002b818c2101ca5dd460800293010705e81ce0594b0fd4e964476db660800a9c1d6bd7180cb2443e80d4a6b080f072c763a0000e5004266807f7940052ba00eedd00216e803b064017dea012c9d00c331800e98c03e02a0115350020be800fb3306e1c9eb22713911a8815226b4fa60d1414e64e556ab2e5f28562a95ca95aaf569ab5c4b269bf534ba7538d4c96600251500a7a6804004c03183200cc1900410c80488610e01f41900f2f280441b4005a7a00ac1900c90c8003064022832012c18d5ba97493751e9c57a268cd34b22d0c2b40a4505e7523746eca51b0ddecafac59129942a558dcd73675eef6f961926eece4eb36defda074ea1ebb70688c56ad550862c3e1888f80094e089080a221c05818428184c182fe00dc0e43a40000

**Comment by diegomura** [comment]
Hey!
Sorry for that. The hyphenation api changed a bit. Now instead of receiving the words array, the callback is called once per word. You can see the fix [here](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c271802800607a5c02403780ee4980098825400d880318086112e1400588680beb9a2c9035c00cdc0414b80359c24632140810476003400088802875ea45300b6496804f005cea011006959f2225ad3c025006e2d1f402f8c8d06001226000e1c706082e000c24cb4b400464c0c52982420301428ea00bc007cea983aeaa9e92850064c41296914d97900dac51400bace5ace6e1e0ce068ea6826b4709959ea00ca10fd7023a170d00cf02c7098dabae8001e1016cbba7ae22348005e7016004c00acaa85baf6c086c6e656b672e28eba3c4e1d5a5d603d00824141d97cb396af9428007800228c002b818c2101ca5dd460800293010705e81ce0594b0fd4e964476db660800a9c1d6bd7180cb2443e80d4a6b080f072c763a0000e5004266807f7940052ba00eedd00216e803b064017dea012c9d00c331800e98c03e02a0115350020be800fb3306e1c9eb22713911a8815226b4fa60d1414e64e556ab2e5f28562a95ca95aaf569ab5c4b269bf534ba7538d4c96600251500a7a6804004c03183200cc1900410c80488610e01f41900f2f280441b4005a7a00ac1900c90c8003064022832012c18d5ba97493751e9c57a268cd34b22d0c2b40a4505e7523746eca51b0ddecafac59129942a558dcd73675eef6f961926eece4eb36defda074ea1ebb70688c56ad550862c3e1888f80094e089080a221c05818428184c182fe00dc0e43a40000)

I just realized the docs are not updated. I'll do that now.
Thanks!

**Comment by redcranesolutions** [comment]
Thanks for the fast reply @diegomura.
