### ISSUE TITLE
Image container is bigger than image

### ISSUE THREAD

**Issue by maxaggedon** [diegomura/react-pdf#436]
**OS:** macOS

**React-pdf version:** 1.1.1

**Description:** 
Image in portrait format (ratio < 1) with a maxWidth style are centered in a container of that width.

For example, if we have an image which is 300x400 and we style it with `{ maxWidth: 250, maxHeight: 250 }`, then the container's width will be larger than the image itself, like so :

<img width="405" alt="capture d ecran 2019-01-08 a 10 17 30" src="https://user-images.githubusercontent.com/17004545/50821144-b3f34a00-132e-11e9-9da2-cee95a99f934.png">

**How to replicate issue including code snippet (if applies):**
```javascript
<Image
  style={{
    maxWidth: 250,
    maxHeight: 250,
  }}
  src={url}
/>
```

**Comment by diegomura** [comment]
Yes indeed. This is made on purpose so the image doesn't get scaled incorrectly. I understand this might not be the ideal scenario for every case.
What's the result you're trying to achieve?

**Comment by diegomura** [comment]
I don't think the issue is in yoga 🤔 
What API do you propose to define where you want the image aligned? I cannot set left as the default align, because there were some people that wanted it centered.

**Comment by diegomura** [comment]
I think [`object-fit`](https://css-tricks.com/almanac/properties/o/object-fit/) and [`object-position`](https://css-tricks.com/almanac/properties/o/object-position/) would be a good approach for this

**Comment by diegomura** [comment]
Ohh got it. Sorry for miss-understanding this.
I do think that the `object-fit` and `object-position` are good features to have though. 
I'm going to publish a new version now, and then work on this to be included in the next after that

**Comment by diegomura** [comment]
Hey @maxaggedon 

I looked at this, and unfortunately there's no much I can do about it. Because how Yoga works, even when defining `maxWidth` instead of just `width`, `widthMode` is always `Yoga.MEASURE_MODE_EXACTLY`, which makes impossible to change when ratio < 1.

I think this is because in Yoga every node has `display = flex` and `flexDirection = 'column' by default. I tried defining `alignItems = 'flex-start'` to the images container, and I got the result you want:

<img width="659" alt="screen shot 2019-01-19 at 2 04 21 pm" src="https://user-images.githubusercontent.com/5600341/51429977-3ca59c00-1bf3-11e9-838f-1cd0459e8009.png">

To be able to achieve this I had to make some changes on the measure function of `Image`. I think this is the closest we can get to the desired result.

**Comment by diegomura** [comment]
Btw, this is the snippet that produced that image:

```jsx
<PDFViewer style={{ flex: 1 }}>
  <Document>
    <Page style={{ padding: 50, alignItems: 'flex-start' }}>
      <Image src="/test.jpg" style={{ maxHeight: 100, maxWidth: 100  }} debug />
      <Image src="/test2.jpg" style={{ maxHeight: 100, maxWidth: 100  }} debug />
    </Page>
  </Document>
</PDFViewer>
```

My apologizes if I wasn't clear enough about the root of this issue. Yoga can be sometimes cryptic to understand 😅

**Comment by maxaggedon** [comment]
Hey,

I will only have the time to take a better look on this later on this week, but it seems great!
From what you say about Yoga, it does exactly look like what I figured while debugging and was trying to express [there](https://github.com/diegomura/react-pdf/issues/436#issuecomment-453943433).

Great work and reactivity on this repo anyway ;)

**Comment by maxaggedon** [comment]
Hey @diegomura ! It took me a lot of time to get back to you on this, sorry.
It works fine with `alignItems: "flex-start"`.
Thanks again !
