### ISSUE TITLE
Transfer repo to @react-pdf organisation

### ISSUE THREAD

**Issue by DuncanMacWeb** [diegomura/react-pdf#463]
It would improve the presentation of react-pdf and be easier for some companies to support the project (either by using/contributing to the code or contributing financially) if the main repo were also under the react-pdf GitHub organisation... 😄 see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/)

**Comment by diegomura** [comment]
Hey @DuncanMacWeb ! This is a perfect valid question 😄. I understand why by having the @react-pdf org this might be the case, and I thought about it many times. The truth is that I also have my reasons why not to do it.

I started this project on my own, and to be honest I never though it would be successful when I started around two years ago (I guess it would be better for me to say that I always saw the potential, but it's not true 😂). Because of that the project was under my name at start.

However, that fact kind of remain the same. Even though the amount of contributions has increased significantly these past weeks (like yours, to which I'm very VERY thankful and excited), the truth is that I'm currently the only active maintainer of this lib. The amount of hours I dedicate to the project is quite a lot (of course, variable in terms of amount of issues and my social life haha), so keeping it like this is one of the paybacks I get.

Hope this doesn't gives the wrong image about me or the reasons why I work on this project. What I mentioned is not even in my top 3 of reasons. I've been trying to onboard new maintainers to the project actively, but unfortunately without any luck so far. I know that the day that changes I will be more than pleased to transferring everything to the org (which may be soon in the future!).

The org was created basically to separate the continuing increasing amount of dependencies I forked/created to this project, from my other personal repos.

Anyway, I do not get that much why people would be reluctant to contribute with code, specially if they are getting benefits by using react-pdf. However, I'm glad to have this written here since it's not the first time I got ask this.

Do not hesitate on giving your point of view! In the meantime I'm going to close this issue since it's not really an issue 😄

**Comment by DuncanMacWeb** [comment]
Haha sure, I understand, particularly your point about onboarding maintainers. From me this about corporate/legal bureaucracy, not about whether _developers_ would want to contribute code. Some companies/organisations have internal rules and criteria that might not be ideal, but they exist for reasons and for better or for worse, we need to pay attention to them ;) so I guess there’s a balance to strike. For us right now, I think it will be OK, but it’s worth bearing in mind in the future.

**Comment by DuncanMacWeb** [comment]
News just in: in the particular case of my company the legal people have approved that we can use and contribute to react-pdf 🎉 (in record time apparently, and good thing since I already did that lol).

More generally though, other corporates probably have similar processes and I thought perhaps that in the future the yoga-layout site for example might be more willing to include react-pdf (#303) if it's all under a more official-looking react-pdf org.

**Comment by diegomura** [comment]
Those are great news!! Thank you very much! It's really appreciated it.
You are right about it. I never consider that as part of the argument why not transferring the repo, and I'll soon take a second thought about it 😄 

Btw, I've always said it, but the opencollective account is open to everyone who wants to dedicate some time in the project and get something in return. So if you or anyone reading this wants to dedicate some time adding new features (there are a bunch of them in the issues), do not hesitate to ask about it!

Unfortunately about the yoga webpage they currently seem very reluctant on adding a project there that doesn't belong to the Facebook ecosystem, or at least that's my guess. Hope in the future that changes because can be really
