### ISSUE TITLE
Strange underline character is added at the end of each words that have "İ" (Turkish language character)

### ISSUE THREAD

**Issue by knot123** [diegomura/react-pdf#489]
**Describe the bug**
Strange underline character is added at the end of each words that have "İ" (Turkish language character)

**To Reproduce**
Put "İ" character in Text. ex. "İçin". You can check that in https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3a0064000e748c074d2a007a5d7d774a60de017760ba0666567602006e323200317028595b0c3e24683b3c0e0072732828000708002e20a0e02530002b39601110042547111e5cd95046209e669e14209124790820bf006b20806659004655800620c72c99802510452810007d50301b485720db03f47a700b8857005a4511256780770c796dd6590aa384a001a0e0489c3c4612044421a8c04afb438804a3055282526933b406086080e06000651318809960c36580b91e260f0120e2285470ba6692ad6251f8f8da10254e18b75bad4194344712cd63b132024e2c81290002f0c1c2002c02c9630faf93000085d047461c2004c2acd261f40041499f0c07092b0058985b08325a00ead9ad7c5c9091d9a3f941d290e86c2004488bba0638c2d5062c8bb2b300a05c1a3a4722c1b2d8f054442a1d05820b1031400000 

**Expected behavior**
To not render underline at the end of the words which has "İ" character

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [chrome and safari
 - React-pdf version v1.3.1

**Comment by diegomura** [comment]
This is happening because [hypher](https://github.com/bramstein/hypher) (the lib we use to break words) apparently does not have support for [Combining Diacritical Marks](https://www.fileformat.info/info/unicode/block/combining_diacritical_marks/index.htm) (in this particular case, [U+0307](https://www.fileformat.info/info/unicode/char/0307/index.htm) is the char causing troubles). I debugged this library but I don't know the algorithm enough to solve it. This happens even if you define the turkish patterns.

I'm going to test some other alternatives for word breaking (hypher seems to be unmantained. Last verision was 2 years ago). [hyphen](https://github.com/ytiurin/hyphen) may be a good alternative

**Comment by diegomura** [comment]
Done! I tried your snippet and the issue is gone. I still recommend you to implement your own hyphenation callback if you want to render turkish text. You can easily do that by:

```js
import createHyphenator from 'hyphen'
import patterns from 'hyphen/patterns/tr'

const SOFT_HYPHEN = '\u00AD'

const hypenator = createHyphenator(patterns)

const hyphenate = (string) => {
  if (string.includes(SOFT_HYPHEN)) {
    return string.split(SOFT_HYPHEN)
  }

  return hypenator(string).split(SOFT_HYPHEN)
}

Font.registerHyphenationCallback(hyphenationCallback)
```

**Comment by knot123** [comment]
@diegomura Thanks, I have installed the v1.4.0 but it didn't fix automatically so I used your snippet (your last comment) and everything works perfectly.
Regards.
