### ISSUE TITLE
What is the best way to achieve the effect of maxLines, when working with a list?

### ISSUE THREAD

**Issue by emorling** [diegomura/react-pdf#521]
I need something like maxLines, but for multiple Text(s) in a View that make up a list. Is it possible? The items in the list have dynamic content, so I don't know how many lines they make up. 

Is there a way to add new lines \n or `<br>` to a Text? Then we could use one Text and maxLines

**Comment by diegomura** [comment]
There's no direct way of setting `maxLines` for multiple Texts. Next version will have a more solid support for `maxLines` and `textOverflow` styling properties.
What you can do is having one `<Text />` and adding new lines inside of it. `<br>` will not work since it's an html tag, but you can achieve the same by:

```jsx
<Text style={{ maxLines: 10, textOverflow: 'ellipsis' }}>
  Something{'\n'}else
</Text>
```

or even create your own `<Br>` will work (I think):

```jsx
const Br = () => '\n';

// ...
<Text style={{ maxLines: 10, textOverflow: 'ellipsis' }}>
  Something<Br />else
</Text>
```

You can also add more `<Text>` tags inside the root `<Text>` to apply inline styles
