### ISSUE TITLE
Feature: Support text indentation via fontkit

### ISSUE THREAD

**Issue by kenblizzardcaron** [diegomura/react-pdf#534]
I was trying to use the `text-indent` CSS property to formalize paragraphs a bit. I did a bit more research and saw that pdfkit uses an [`indent` option](http://pdfkit.org/docs/text.html#text_styling). That'd be perfect but it isn't [supported](https://react-pdf.org/styling#valid-css-properties).

I'd like To be able to use a `textIndent` type style to indent the first line in a multiline wrapping `Text` component.

I've considered as alternatives:
- Hacks with tab characters and spaces 😦
- Just use pdfkit I guess 🤷‍♂️
- Have a custom element just for the first line 👎

This is an amazing library by the way!

**Comment by diegomura** [comment]
Thanks for reporting this @kenblizzardcaron !
Adding this feature wouldn't be that simple as relying on the pdfkit `text-indent` option. This is because we don't rely on pdfkit at all to render text in the document, but we do it by using [fontkit](https://github.com/react-pdf/fontkit), which is way more powerful that the built-in solution of pdfkit. This means something has to be added there to support this. I don't think it would be that much work though. I'll try to find some time to do it, or if you want to can give it a try!

Thanks again
