### ISSUE TITLE
Use of justifyContent doesn't break line

### ISSUE THREAD

**Issue by skjo0c** [diegomura/react-pdf#575]
I am trying to make a pdf that contains a certain item in left and some in right. I tried following, but line break isn't working.

```
<Document>
    <Page style={styles.body}>
      <View
        wrap
        style={{ flexDirection: 'row, justifyContent: 'space-between' '}}
      >
        <View
          wrap
          style={{ flexDirection: 'column'}}
        >
          <Text>
            Brand Name
           </Text>
        </View>

        <View style={{ flexDirection: 'column'}}>
          <Text>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus at lacus nec facilisis. 
               Pellentesque eu nulla elit. In placerat mi sed suscipit feugiat. Aliquam at egestas nulla. Fusce 
               ornare massa a finibus faucibus.
           </Text>
        </View>
      </View>
    </Page>
  </Document>
```

**Comment by skjo0c** [comment]
I will close this issue as I have found solution for it. Following is a solution I am using if anyone is searching for it.

```
<View style={{flexDirection: 'row'}}>
        <View style={{ width: '20%' }}>
          <Text>Brand Name</Text>
        </View>
        <View style={{ width: '50%', position: 'absolute', right: 20 }}>
          <Text style={{ textAlign: 'right' }}>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus at lacus nec facilisis. 
               Pellentesque eu nulla elit. In placerat mi sed suscipit feugiat. Aliquam at egestas nulla. Fusce 
               ornare massa a finibus faucibus.
          </Text>
        </View>
</View>
```

**Comment by skjo0c** [comment]
Actually, the position absolute is ignoring the parent background and heights, so had to reopen the issue.

**Comment by diegomura** [comment]
Isn't [this](https://react-pdf.org/repl?code=3187b0760ce02e0040a200f021816c00e01b0298c0bc3002804a3c03e1806f00a06180272ca015ceb109b69801e004446098a2c60a290e9cb80052401ccb18ce1201a804b2c01dc634009ed97050a00cdb021e2a1b0282bc002e1801c8e8875f600d0c00564da0ac3da030b81430941dbd841a123016002d0011a33a96309b8c1c5440358c9393180009a046081d1854080a12197d802fb542a2b29aa68e9e818c3a8a9e540005984013000300293d8c2d7d4344800a96022880109d123e4c001caa1617003d0cdcc4c376ea86bee29711f3542e963e853b674f58402b30cd5d78a4f72eec0b75db705cc0104302a19180c27410774a0a371bbc3e8a000cb14b028180a8d010410c0f220229d0b42a5806ca0ee50240b096460b060483cba25410600a8c032181618150001d0c0812a0023931503043120984cb8b7869b00c14525600a70aa22a6044019dcb87c368927676044580800a7058260c0c04c0c0cad91cee40124d8982896096b0140a8b4583c969bc4cb421385c6990a92adcde40a8595365c9a0480829bcd32ee400c5bd380d66b8a60240306015080409034e17325412d8c8ac525ef272d3121dacd4435c39344edc2db9df6db691c9eadb3e00884227a91000dc546a950a800252c144a0921e227390c7c93a085c442a130382da9047542000) what you need? `justifyContent` worked well for me.

Because how Yoga works, the issue with the first snippet you shared is that you need to specify some width when many texts layout horizontally (you did it in your second snippet using `%`). Unfortunately I couldn't find a way of making it work without the `width` definition
