### ISSUE TITLE
Re-Render Error JS appendChildBefore after modify state

### ISSUE THREAD

**Issue by jbrat** [diegomura/react-pdf#621]
Hello diegomura,

I have a problem with the @react-pdf/renderer functions :
![image](https://user-images.githubusercontent.com/15637356/58689008-389a3f80-8386-11e9-8893-4dfbfa0f415c.png)

When i try to reload the PDFViewer Document when state update, the reac-pdf function try to do a "appendChildBefore" but it isn't a function in Javascript ?

My Component :
image
![image](https://user-images.githubusercontent.com/15637356/58689018-3e902080-8386-11e9-80e0-5ec95ba9adf3.png)

I have an array of pages, when i click on a checkBox (handleCheckPage) i can hide or show a page in the pdf. When the action of loadPages was call (modify status show on my pages) the state was updated and render the component, i have the error.
At start the PDF loading correctly but when i try update state, it's fail.

You should probably don't use a "appendChildBefore" function that doesn't exist in JS ?

Thank you for answering,
Bye

**Comment by nero2009** [comment]
Try adding a `key` when you map through the pages array.

**Comment by diegomura** [comment]
Please try what @nero2009 suggested.

It's hard, not to say impossible, to know what's going on by your image (also, it's much better to share the code for people can just copy).

If this persist, please provide a simple example I car use to replicate

**Comment by jbrat** [comment]
Hello, 

Thank you for your answers.

I try to add a key but the problem persist.

Link to a simple code example : https://codesandbox.io/s/charming-maxwell-j6oym

When you try to check the "Show page 1" you have this error   
![image](https://user-images.githubusercontent.com/15637356/58801169-0ef14a80-860a-11e9-9bc4-3cf55ee003f3.png)

Thank's for answering

**Comment by Maddrobots** [comment]
Hello,

I am having the same issue. Here is a simplified version of what I am doing:

```
return (
  <Document>
    {records.map(record => (
      <Page key={record._id}>Record {record.title}</Page>
    )
  </Document>
);
```
If my records array changes, React translates that to adding or removing Pages to/from the Document. The trouble comes from adding a record before an existing one. This translated to adding a Page before existing Pages which causes the same error @jbrat shows above.

In other words, selecting the second record in the image below does NOT cause a problem because it adds a Page to the document AFTER an existing page
![image](https://user-images.githubusercontent.com/5360333/107858742-ae5c6e00-6dea-11eb-849a-6a8c721069be.png)

However, selecting the first record in the image below DOES cause the error because it adds a Page to the Document before an existing page, hence the error: TypeError: parentInstance.appendChildBefore is not a function.
![image](https://user-images.githubusercontent.com/5360333/107858825-0dba7e00-6deb-11eb-9fbe-46198df7a17c.png)

My current workaround is trying to force React to re-render the entire Document instead of just adding Pages but it seems like either something should be changed internal to the library to handle this case or I am using the library incorrectly. Please advise.

Thank you!

**Comment by diegomura** [comment]
Should be fixed on latest version. Please report back if this still persist. Thanks!
