### ISSUE TITLE
Types are incomplete for Style

### ISSUE THREAD

**Issue by bkoltai** [diegomura/react-pdf#687]
**Describe the bug**
The type declaration for `Style` is incomplete and unnecessarily duplicates information available from other sources of truth.

**To Reproduce**
One example:
1. Attempt to use `justifyContent: "flex-end"` in a `Stylesheet.create({...})
1. Notice the TS error

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
Shouldn't have a TS error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - React-pdf version 1.6.4

**Comment by bkoltai** [comment]
I propose using the [`csstype`](https://www.npmjs.com/package/csstype) library to ensure the typing information stays up-to-date and correct for all the supported CSS properties, similar to [`styled-system`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-system/index.d.ts)

**Comment by joelgallant** [comment]
related was https://github.com/diegomura/react-pdf/pull/696

any idea which others are, for a quick win? agreed on using something like csstype

**Comment by diegomura** [comment]
Hey! Not sure about using csstype, since react-pdf does not support all the CSS spec. Adding these types will give a confusing idea that we do, creating a lot of frustration when some don't work. Pinging @rzymek who did the original styles types. I would be happy to merge any PR that fixes missing types

**Comment by rzymek** [comment]
react-pdf supports only a small subset of CSS. The properties that are supported often expect only a subset of values specified in CSS. I did my best to extract all the used properties and values into the typing. The usage spans across a few packages, so it was inevitable that I missed some. Thank you for improving it with #696. I think this is the way to go. Polish the current typing instead of starting from full CSS spec and trimming it to supported subset.

**Comment by rzymek** [comment]
In the subject - there are two PRs improving the style typings: #689 & #703 
@diegomura: Could you merge?

**Comment by rzymek** [comment]
Added another one of my own #708

**Comment by diegomura** [comment]
All merged! Thanks for your effort. I’ve been traveling these past few days and couldn’t dedicate that much time to the project but I’ll soon!
