### ISSUE TITLE
textAlign Right is making the text go outside of the canvas

### ISSUE THREAD

**Issue by dorwastaken** [diegomura/react-pdf#816]
Bug description:
Trying to generate a table with rows and columns in Hebrew
For that, I'm using `textAlign: 'right'` method to align all my text to the right side, in addition to `flexDirection: 'row-reverse'`
````
const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
  },
  rowA: {
    textAlign: 'right',
    backgroundColor: 'red',
    flexGrow: 4,
  },
  rowB: {
    textAlign: 'right',
    backgroundColor: 'red',
    flexGrow: 2
  },
  rowC: {
    textAlign: 'right',
    backgroundColor: 'red',
    flexGrow: 2
  }
});
 <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.row}>
        <Text style={[styles.rowA, styles.text]}>A</Text>
        <Text style={[styles.rowB, styles.text]}>B</Text>
        <Text style={[styles.rowC, styles.text]}>C</Text>
      </View>
    </Page>
  </Document>
````
You can view it here
https://react-pdf.org/repl?code=1407a100818409c14c10c02eb700440f606302b816d601da253ab800ee81862c26940cec40b2027863be47802f38005004a1e00f9fb070e000f3b3cd58788952002bc00e629e804b005eb1b802200820059f7c858aa40354db003bb8462c00d9e80de4f5fd0074d1d1d805f794b4b49001558000f624f77006d589f3f3b43001a474417581f6468805d20c3491008e8e0908970a898ccd76e3704daecdf7f002174c4ef5cc402e156e2d2c4728aaae88cacfac6aca4ff480ea69ceadec801eae1c5629b7b75e2957572e2994e21e001006e60500818046471af5a061ae99e70006526b7800b5858446f4c1c090b03e1b814c90017380c1960019ab922a84d1c130884d250a100726480168e0003758341e8b04c6a41401724499286284c314dd4333934aa02163a02cafa20c916700008de0980035aa8fcd8020004d20e8673a1a0ecd804a797084401c521e063153c094f05b4e9bcc673359ecce773b5120170b45e87154a6572ac4b160ce595d9958a78545d5fe284009829dae4a400d96234b2d9e06c59a3d96c148ac592e96cbe551d16fc08b1f017b223ebb3fa29c000b9d2e0025042a294a80018af90812a25f124ac23b51c0206109680000

**Expected behavior**
Text should not want to make me jump from a cliff and just align to the right side as it usually does

**Comment by oswaldoacauan** [comment]
We are facing the same behavior in our PDFs.

![image](https://user-images.githubusercontent.com/1268518/73731107-2e5fea80-4738-11ea-9f74-d7c1d03e5058.png)

**Comment by geerthoekzema** [comment]
When i'm using flex instead of FlexGrow it displays the wanted behaviour, see [repl](https://react-pdf.org/repl?code=1407a100818409c14c10c02eb700440f606302b816d601da253ab800ee81862c26940cec40b2027863be47802f38005004a1e00f9fb070e000f3b3cd58788952002bc00e629e804b005eb1b802200820059f7c858aa40354db003bb8462c00d9e80de4f5fd0074d1d1d805f794b4b49001558000f624f77006d589f3f3b43001a474417581f6468805d20c3491008e8e0908970a898ccd76e3704daecdf7f002174c4ef5cc402e156e2d2c4728aaae88cacfac6aca4ff480ea69ceadec801eae1c5629b7b75e2957572e2994e21e001006e60500818046471af5a061ae99e70006526b7800b5858446f4c1c090b03e1b814c90017380c1960019ab922a84d1c130884d250a100726480168e0003758341e8b04c6a42ce00009a69e864673c05858f8544c914eea199c9a55010b1d02e57d10ac89005c91264a18a130c50008de0980035aa8fcd80225320e8673a1a0bcd8252858a2d6528950802328b14ccc89638c988508bc16d49453650aa57a0556a8d56ab12c5833935767d4490dc6f000099cd124b562c3b6e179b929027659e09cee7aa88d45e7f30591f00bb15cad57ab35daf026295bf02107c0d1f2ec6edc000b9d2e0025042a294a80018af90846e81f124ac23b51c020610b680000)

**Comment by Flaxxas** [comment]
Got another [repl](https://react-pdf.org/repl?code=3187b0760ce02e004012053021804c102718178600a0253601f1e0140c3003c01a8096080ee3340278036096037ab1c401d000b6469d005f22e4295002a0800794228951b5a6012500f473164e9b216c34008c02b80736651da71e36fbf5060a126050273d7ee63a806620e800b648e850b4e0daba4a52da748c92f8a4a4ced03000b22c002220c06641082ed878845824b8b13979052efad294000a481608ccb4005e9c00440082002c5dd6b6dcbc0802000ecd08125206942aa2305a7514da4d2d75da55f98531f800dcc9a9b0a310c500ca0e08e7c208504ee8c85008b85c52932d005c306f067e1cf22cad11eee08981be0072501b1f26008548c4001a2930950186fafda45a2d0c11e4110000ddd456408c18082241802cc49814104b4339404030284806141384c018b4361b060210035ab5664b1c73d143d35059c12cf42d02c8228042962ce02ec30ca8620405302419c14e3043b810281808bfe0a20483c2e0487a0400c087220c002b33341687e1600185c0cf17242209335401684c77060210a4e91485d0d49940118000c08e7592fd6e28063cd7ef387410df44c0099d3146c6cbe58ae56534d50f57a1952870043605af400b112c8e1f895bab01d6dd1eaf53799ed817f0cd067154125f299442e50aa5423486203b24004ac877034b200317e23c07185c25132db1aac1961ba00000) with this issue. 
`flexDirection: row` is breaking `textAlign: right || center`.

**Comment by Apollinaire** [comment]
I had the same problem, with a container that has `justifyContent: 'space-between'`, and the rightmost item had Text with `textAlign: 'right'`. I had to remove `space-between`, and instead added `flex:1` to each item inside the container.
It seems that the root of this issue is some defaults that are not set on View components that are children of a `display: 'flex'` View. 
The difference between `flex: 1` and `flexGrow: 1` is that the flex shorthand also sets flex-shrink: 1 and flex-basis: 0.
After some testing **it seems that `flexBasis: 0` is required when using `flexGrow` to wrap some aligned text.**

**Comment by diegomura** [comment]
Fixed in latest build
