### ISSUE TITLE
Image is not working wirh create-react-app

### ISSUE THREAD

**Issue by Canopix** [diegomura/react-pdf#883]
**Describe the bug**
I'm trying to put an image import into IMAGE component from @react-pdf

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. import and image like `import logo from '../assets/image1.png` (something like this)
2. put `<Image src={logo} />`
3. The image doesn't appear on the page.

**Expected behavior**
I want the image that I imported on the pdf.

**Comment by theluk** [comment]
if you read the documentation properly, you will see that you need to provide a source object.

https://react-pdf.org/components#source-object

which is in your case something like this

`{ uri: logo, method: 'GET', headers: {}, body: '' }`

**Comment by Canopix** [comment]
@theluk first for all, thanks for your response. 
Second, it seems to be evident that I already read "properly" and tried every option that the documentation has, and as the last option, I come here to ask something like this. 

I already tried with that option without any result. The images didn't appear.

**Comment by theluk** [comment]
Sorry for that, I just was referring to the steps to reproduce and that is the wrong syntax. 

Can you please then update your steps to reproduce because this way you describe it it is not supposed to work unless you are in node

Also the console logs often useful information about loading errors. Do you have any?

**Comment by Canopix** [comment]
Everything works fine now!! :)
