### ISSUE TITLE
Border-radius support for Pages

### ISSUE THREAD

**Issue by grumpyTofu** [diegomura/react-pdf#892]
For some pdf documents, it would be really helpful to have support for pages with curved edges. I have attempted the following code with no luck:

```
<PDFViewer width='100%' height='100%' frameborder="0">
  <Document>
     <Page size={{width: 1.3*72, height: 1.75*72}} style={{borderRadius: 50}}>
        <View style={styles.section}>
           <Text>Section #1</Text>
        </View>
     </Page>
  </Document>
</PDFViewer>
```

Maybe I am missing something in the documentation, but no matter what I try the page in PDFViewer always comes out perfectly square. Is there any chance for future support of curved pages?

**Comment by geerthoekzema** [comment]
I don't think this will be supported because the pages cannot have border-radius. I've never, ever seen an PDF with rounded corners. Not in react-pdf, but also not in software like indesign, illustrator.

Afaik this is simply not possible within the PDF standard.

What you could do is add an <View /> element in the background with rounded corners.

**Comment by grumpyTofu** [comment]
@geerthoekzema 

Makes perfect sense. Thank you for suggesting an alternative! I will try that and close this issue.
