### ISSUE TITLE
Isssue with missing dependency 'lodash.isnan' in '/node_modules/@react-pdf/core/lib/elements'

### ISSUE THREAD

**Issue by AggarwalAnkit** [diegomura/react-pdf#97]
Hey guys, could you please help me with this error

../~/@react-pdf/core/lib/elements/Text.js
Module not found: Can't resolve 'lodash.isnan' in '/node_modules/@react-pdf/core/lib/elements'

I created a react app using creat-react-app and added following:
`yarn add @react-pdf/core`
`yarn add @react-pdf/node`

After that, I copy pasted the sample code given on git (https://github.com/diegomura/react-pdf)

Do I have to install this missing dependency?

**Comment by diegomura** [comment]
you shouldn't. let me take a look

**Comment by diegomura** [comment]
Fixed in `v0.2.2`.
Sorry about all that logs.
Also, please consider using something else than `create-react-app` to test `@react-pdf/node`. I uploaded [this gist](https://gist.github.com/diegomura/eccbf3dd4c277e0b73547e581eb0ab3e) where I show how simply you can build a test project for this.

Thanks!

**Comment by AggarwalAnkit** [comment]
Thank you very much @diegomura . I am new to react, so couldn't fix it on my own :)
